### ISSUE TITLE
HTTP file upload certificate issue

### ISSUE THREAD

**Issue by antonyablonsky** [ChatSecure/ChatSecure-iOS#1007]
I’ve launched my personal XMPP server for secure messaging, everything works, but I can’t send and receive photos. App says that certificate is not valid, and never let me send or receive photos. Since server I’m connecting is under my property, and of course I can really trust this connection I don’t need to have not self-signed certificate. Can you let people decide send photos or not in any server connections? Maybe put toggle switch in settings with that option. Thanks

**Comment by licaon-kter** [comment]
Just import this certificate on the device.

**Comment by antonyablonsky** [comment]
Imported certificate (I'm using ejabberd, so I imported server.pem). Also tried to reconnect to server, app says that certificate is correct. But when I send photo I get that annoying "certificate for this server is not valid. maybe, you're connecting to server, which imitaitng "my_server", what can put a risk on your confidential info. resending will use omemo"
