### ISSUE TITLE
TestFlight to expire soon

### ISSUE THREAD

**Issue by mimi89999** [ChatSecure/ChatSecure-iOS#1029]
Current TestFlight will expire in 4 days.

**Comment by mimi89999** [comment]
It is possible to install the version from the AppStore and keep data.

**Comment by Spydar007** [comment]
@mimi89999 how did you manage to do that? It shows with an Open button in the App Store for me because the versions are the same. @chrisballinger can we please get a new build of some description so that I don't have to delete the app and start again with new keys?

**Comment by mimi89999** [comment]
@Spydar007 I had a download button in the AppStore.

**Comment by Spydar007** [comment]
Unfortunately mine is sat at "Open", which is the behaviour I would expect considering the versions are the same.

**Comment by mimi89999** [comment]
Does it open?

**Comment by Wiuma** [comment]
Installed the App store version over the beta and it works. No new configuration needed.

**Comment by Spydar007** [comment]
This was not the case for me and I had to completely delete and redownload the app before I could get it to work, which meant resetting my OMEMO keys and all chat history.
