### ISSUE TITLE
App disconnects in Background and Stops Push

### ISSUE THREAD

**Issue by racsnet** [ChatSecure/ChatSecure-iOS#1032]
Hi
I have a problem with Chatsecure on our ejabberd Server (Version: 18.04)
mod_push is enabled and working according to Chatsecure.
But if the App goes into background (not swiped away) first the Contact gets the status "away" and then after some time it completely disconnects and stops receiving push.

Any help on this problem?

**Comment by licaon-kter** [comment]
There where some improvements to push in 18.06, enable **mod_push** and **mod_push_keepalive** see if it helps.

**Comment by racsnet** [comment]
thanks for your advise

it seems like now its running realy great. beside the fact, that the contact keeps going away. but this is not realy a problem.
