### ISSUE TITLE
ChatSecure v4.3.2 crashes direct after start

### ISSUE THREAD

**Issue by maitrenageur** [ChatSecure/ChatSecure-iOS#1035]
The new update to 4.3.2 crashes one second direct after start.
I use iOS 11.4.1.
I heard, that under iOS 12 beta, it is still running.

**Comment by FeisTy-H** [comment]
Hi, same issue here for me. Since the update on 4.3.2 the application is not usable anymore. Even after a complete reinstallation and reboot.

**Comment by chrisballinger** [comment]
There was a crash introduced with v4.3.1: https://github.com/ChatSecure/ChatSecure-iOS/issues/1034

Nothing about the code itself changed between releases other than the Swift compiler version used, so I think the only solution is to disable that code completely. I tried to work around it, but it didn't work.

**Comment by jh-cg** [comment]
I have iPhone 4s with 9.3.5, hit this crash after upgrade, but complete reinstall fixed that for me.

**Comment by chrisballinger** [comment]
v4.3.3 is out which should resolve this issue

**Comment by FeisTy-H** [comment]
Thank you for the workarround and/or fix. It works for me ! Just need to reinstall it. Thank you Chris

**Comment by maitrenageur** [comment]
Thank you Chris for the fast support. It works.
