### ISSUE TITLE
Please publish this app to China App Store.

### ISSUE THREAD

**Issue by scubajeff** [ChatSecure/ChatSecure-iOS#1037]
Why this app is not available in China App Store?

**Comment by nsuchy** [comment]
@chrisballinger Wonder if there are alternate ways to distribute the app which wouldn't violate the developer agreement with Apple.

@scubajeff If you also have a macOS Device and don't mind getting your hands dirty you could compile the app from source and install with Xcode. I understand it's not ideal but it's a short term solution for you.

**Comment by Echolon** [comment]
May it is possible t offer "just" some "kind of VPN", which would may allow to use TOR, too? But I don't really know what I am talking about.
But maybe it's a compromise to offer the app without TOR in the end

**Comment by nsuchy** [comment]
@chrisballinger No one would ever dare attempt to circumvent censorship in China. Oh wait...
@scubajeff I just realized that you could download an "IPA" file of ChatSecure and install with Cydiaimpactor no MacBook required. See: http://www.cydiaimpactor.com keep in mind that ChatSecure does NOT support Tor bridges at the moment so Tor won't work inside China.

**Comment by kitkatloyalist** [comment]
create a plugin option allowing the user to "find" plugins? 

> distribute the app which wouldn't violate the developer agreement with Apple.

What's the apple way to beta test apps by invitation or private url?  i can't recall the apple term. Xabber is employing it now

**Comment by nsuchy** [comment]
@kitkatloyalist TestFlight?
