### ISSUE TITLE
App Broken

### ISSUE THREAD

**Issue by irlcatgirl** [ChatSecure/ChatSecure-iOS#1041]
I use ChatSecure on iOS. Anytime I send a message the chat window blanks out and won't work further. The app is basically in an unusable state at this point. Is there a way I can send a crash dump or whatever to the developers?

**Comment by mightyBroccoli** [comment]
I guess there are 2 options you have.

- there is a Chatroom where some of the community members and sometimed even the dev himself are trying to solve
- anonymise the dump and append it to this issue

**Comment by chrisballinger** [comment]
Can you try "scrolling down" when it blanks out? I'm pretty sure this is a known bug that is intermittent and haven't been able to track down the root cause.

**Comment by nsuchy** [comment]
@chrisballinger No it's not that bug, I cannot send or receive messages at all. Emphasis on can't send. I wasn't receiving on another xmpp account on pidgin I setup for test purposes. Uninstalling and reinstalling the app fixed the issue for me although I lost my OTR and OMEMO keys 😭 and it happened with all chats.

**Might be able to reproduce issue:**
* Be on latest iOS 12 developer beta on iPhone 7
* Have two XMPP accounts added
* Message a few people
* Join a MUC (tails@conference.riseup.net for me)
* Delete all chats and close the app
* Reopen to a bricked hat secure

**Comment by chrisballinger** [comment]
Oh, perhaps this is an issue with iOS 12.

**Comment by nsuchy** [comment]
@chrisballinger You should test your app on iOS 12 - September is coming up soon 😨
