### ISSUE TITLE
ballinger.io has an outdated certificate

### ISSUE THREAD

**Issue by mimi89999** [ChatSecure/ChatSecure-iOS#1047]
`lebihan.pl‎: Establishing a secure connection from lebihan.pl to ballinger.io failed. Certificate hash: 2341ae48bbdc5f1e18a7411bedd42efabfbbcb8cc3cdc757e5948cc8d1edc0f0. Error with certificate 0: certificate has expired. `

**Comment by chrisballinger** [comment]
time to switch to letsencrypt
