### ISSUE TITLE
Push dont work

### ISSUE THREAD

**Issue by HelpITru** [ChatSecure/ChatSecure-iOS#1051]
After 15-20 minutes turning off the phone (Iphone iOS 11.4)  push stop working. 
Tried several different servers - everywhere the same problem. At the same time, clients on Android (example https://conversations.im/ )  work perfectly and receive messages and status buddy.
How can I fix this problem ? 
To call and hang up to write off in the messenger is nonsense. 
The first five minutes after turning off push work fine, then stop. I think this is a critical problem for the messenger. 

The second question : I can't understand how and why the protected text is transmitted in push ? In the incoming push shows from whom and the text of message itself - it turns out it is transmitted without encryption ? Its normaly for secret messaging ?

**Comment by licaon-kter** [comment]
What server did you use?

Did you enable OMEMO for your chats?

**Comment by HelpITru** [comment]
In production use prosody
Yes, enable OMEMO

**Comment by licaon-kter** [comment]
Did you load the needed modules "mod_cloud_..."?

Also, use a current version of mod_cloud_notify (get from trunk) and set: `push_notification_important_body = "New Message!"`

**Comment by HelpITru** [comment]
Yes, loaded mod_cloud_notify
Push's come, but after 10 - 15 minutes off phone stop working

**Comment by sokai** [comment]
> Did you load the needed modules "mod_cloud_..."?
> 
> Also, use a current version of mod_cloud_notify (get from trunk) and set: `push_notification_important_body = "New Message!"`

FYI: That manual setting is not needed anymore (because that's the default setting) like you can see in the module description at https://modules.prosody.im/mod_cloud_notify.html#configuration
