### ISSUE TITLE
Incorrect domain checking of certificates

### ISSUE THREAD

**Issue by mimi89999** [ChatSecure/ChatSecure-iOS#1079]
ChatSecure 4.3.6 and previous versions validate the hostname resolved from SRV records. This is incorrect. Server certificates must be valid for the domain part of the JID. As a result, some valid certificates are shown as invalid:

![simulator screen shot - iphone se - 2018-12-09 at 17 37 32](https://user-images.githubusercontent.com/8530546/49700012-26aac180-fbd9-11e8-8b18-8f804f0cc261.png)

(The domain part of the JID was `jabber.at`)

While some other certificates that should be considered invalid are shown as valid:

![simulator screen shot - iphone se - 2018-12-09 at 17 38 52](https://user-images.githubusercontent.com/8530546/49700017-522dac00-fbd9-11e8-8a28-5766e2272752.png)

(The domain part of the JID was `test.lebihan.pl`)

Showing certificates only valid for the hostname in the SRV as valid could be a security issue as it might be misleading users into trusting those certificates. Many domains don't support DNSSEC and very often DNSSEC isn't validated. An attacker could easily modify the DNS response to point the SRV records to a domain that he controls and have his certificate shown as valid.

**Comment by chrisballinger** [comment]
@mimi89999 The logic has been changed in e46b17e to always verify via `myJID.domain`, instead of from the SRV record. If a user `user@example.com` previously pinned `xmpp.example.com`, they will see a pop-up / local notification requiring them to re-verify their server's certificate for `example.com`.
