### ISSUE TITLE
Asking for a passphrase out of nowhere.

### ISSUE THREAD

**Issue by DiagonalArg** [ChatSecure/ChatSecure-iOS#1131]
v4.3.7, iPhone 5S.

It's been some time since I opened Chatsecure (a couple of months).  I just updated and am trying now, but it's asking for a password, though I never set one.  

I can wipe and start over, but it's not giving me a way to do that either.   I guess I need to uninstall and reinstall?

**Comment by mwlczk** [comment]
You can reinstall the app. It is not going to change your omemo-keys.

**Comment by DiagonalArg** [comment]
Thanks.  I reinstalled.  I don't even see a place in the app to set a password if I wanted to.

**Comment by mwlczk** [comment]
Might be something ios specific

**Comment by mwlczk** [comment]
@DiagonalArg, but did the reinstall solve your initial problem? Did you loose your OMEMO keys and got new ones?

**Comment by DiagonalArg** [comment]
@mwlczk - ya, it solve the issue, thanks.  I didn't have any keys, so that was a moot point (I do now!).  Thanks for your help.
