### ISSUE TITLE
Cannot see OMEMO keys of my other clients

### ISSUE THREAD

**Issue by ichi-i** [ChatSecure/ChatSecure-iOS#1137]
Hello,

I have recently downloaded the latest iOS version of the application.

I noticed that I cannot add (or see) my own keys from other clients. When I go to "Manage My Keys" under account, I only see the OMEMO and OTR key of ChatSecure.

This can be annoying as I can see the messages sent by my contacts via OMEMO but not my own messages unless I sent them via my phone.

How can I add my own keys? Is it a problem with the current version?

**Comment by licaon-kter** [comment]
What do you see? Does your server have Carbons?

**Comment by ichi-i** [comment]
The keys appeared after a few hours. Maybe there were some desync issues?
I'm going to close this issue.
