### ISSUE TITLE
Quote message when replying

### ISSUE THREAD

**Issue by lkrms** [ChatSecure/ChatSecure-iOS#1140]
Apologies if this has already been addressed in another issue, but I wasn’t able to find it if so.

I haven’t been able to find a way to reply to specific messages in ChatSecure, e.g. long press -> reply -> original message quoted (it would be even better if this could be achieved by “linking” to the original message—as Facebook Messenger does—but XMPP threading might not lend itself to this?)

Maybe this is something I’ve missed, but if not, please consider this a feature request. Thanks so much for building such an excellent app!

**Comment by chrisballinger** [comment]
There's no way to do it in the app currently, but it looks like XEP-0201
might be the way other XMPP clients are doing it:
https://xmpp.org/extensions/xep-0201.html
