### ISSUE TITLE
Sending message added ?'s to the end

### ISSUE THREAD

**Issue by ioscanner** [ChatSecure/ChatSecure-iOS#1163]
When I send a message from chatSecure using IOS 4.3.9 (14.3) it add a few ?'s at the end.

Example:  I send "Got it"

The message on the other end get this: "Got it ?  ???? ? ? ?    ??  ?   ??  ??"

I can send thru Monal and I don't have this issue.

**Comment by chrisballinger** [comment]
Use plaintext only, that is likely the OTR hint

**Comment by ioscanner** [comment]
Yes, that was the issue.
