### ISSUE TITLE
Publish old version of ChatSecure on App Store

### ISSUE THREAD

**Issue by sluramod** [ChatSecure/ChatSecure-iOS#1184]
I have an old iPhone 4s with iOS 9.3.6.

It would be nice to be able to install ChatSecure 4.3.9 on it, deployment target is set at iOS 9 for that release. I believe if you go to 'Pricing and Availability' section of appstoreconnect, at the bottom of the page there is Last-Compatible Version Settings section where 4.3.9 can be checked and then available for download on older devices.

**Comment by chrisballinger** [comment]
They are all selected, all the way back to v1.0. You might need to make the purchase on a newer device and then go into your purchase history to download.
