### ISSUE TITLE
Where are the tor connection option? 

### ISSUE THREAD

**Issue by boistordu** [ChatSecure/ChatSecure-iOS#1203]
Is it only available on a rooted iPhone ?

**Comment by licaon-kter** [comment]
They were removed for now.

/close this

**Comment by boistordu** [comment]
Ow okey thanks for the information. Hope it will come back soon

**Comment by cryptedbv** [comment]
Please update the ChatSecure official site and remove TOR. As it is quite confusing. I really hope the TOR option will make a comeback. Cheers for your work.

**Comment by DickSynth** [comment]
Oh damn i really hope i can enable tor with this client... why android can do this with all apps ?! (Orbot)...... 

And ios can't... apple sucks...

**Comment by chrisballinger** [comment]
@DickSynth There was a system wide Tor VPN in progress but we hit memory usage limitations because of the Tor microdescriptors, and the project stalled. https://github.com/iCepa/iCepa
