### ISSUE TITLE
ChatSecure Crash on start - while working fine on simulator

### ISSUE THREAD

**Issue by uzairsabir** [ChatSecure/ChatSecure-iOS#1204]
**dyld: Library not loaded: /System/Library/Frameworks/CryptoKit.framework/CryptoKit
  Referenced from: /var/containers/Bundle/Application/D666341B-ABCA-46D3-9192-939825861FDF/ChatSecure.app/ChatSecure
  Reason: image not found**

**Comment by chrisballinger** [comment]
You need to build on macOS Catalina
