### ISSUE TITLE
OTR fingerprint validation via QR-Codes/ Scanning them

### ISSUE THREAD

**Issue by dwt** [ChatSecure/ChatSecure-iOS#121]
The idea here is that, validating fingerprints is hard work. The socialist milionaire protocoll helps, but if you stand next to each other there is a much easier communication channel availeable between the phones: the camera.

So if I can show a qr code that validates my fingerprint and the other person can then just scan it - that could be way easier.

Bonus points if this allows ne to add the other person to my contact list at the same time.

**Comment by chrisballinger** [comment]
support added in develop branch
