### ISSUE TITLE
Groups / Multi-User Chat support

### ISSUE THREAD

**Issue by Like-all** [ChatSecure/ChatSecure-iOS#129]
I've tried to add a muc as a regular contact, but nothing happened :(

**Comment by sammcj** [comment]
+100

**Comment by dwt** [comment]
yeah! And then some sip to get backgrounding.... :)

**Comment by sammcj** [comment]
Any update on an ETA for this?

**Comment by tibtab** [comment]
maybe with axolotl?

**Comment by kierancrown** [comment]
Is this now supported?

**Comment by chrisballinger** [comment]
Not yet

**Comment by chrisballinger** [comment]
Not to fear! We are now definitely working on this.

**Comment by celebrion** [comment]
Any news about this?

**Comment by chrisballinger** [comment]
Implemented in develop branch

**Comment by pratz11** [comment]
Hi Chrisballinger,
I wanted to implement groupchat in my existing Chat secure code but I am unable to find develop branch code.So could you please post a link for the same.
Thanx in advance!

**Comment by the-solipsist** [comment]
@chrisballinger: From which version does ChatSecure support MUCs?

**Comment by chrisballinger** [comment]
@the-solipsist v3.2. When starting a conversation you can check more than one contact.

**Comment by the-solipsist** [comment]
Can you join an existing MUC?

**Comment by chrisballinger** [comment]
Not currently, you need to be invited

**Comment by tarunbhutani** [comment]
Hi, 
Is multi chat room woking fine in chatsecure?

**Comment by mathisschmieder** [comment]
I really don't see why this issue has been closed. Joining an existing MUC room is impossible unless invited and even that has yet to work for me.

Please, implement joining an existing MUC, or at least give us an explanation why you chose not to.

**Comment by chrisballinger** [comment]
@mathisschmieder We are tracking separately in #480
