### ISSUE TITLE
please help login problem

### ISSUE THREAD

**Issue by Mohamed-Mitwaly** [ChatSecure/ChatSecure-iOS#223]
i have been using following credentials to login to ejabbered
username:-   test1@localhost
password:-    12345678
domain:-      54.83.202.126
port:-           5223
but it gives me 
![ios simulator screen shot aug 12 2014 3 00 22 pm](https://cloud.githubusercontent.com/assets/8158283/3890008/807235a8-2218-11e4-84dd-4afc37478f1f.png)

and in the log it gives me 

"OTRXMPPManager: xmppStreamDidDisconnect:withError:
2014-08-12 14:03:58:634 ChatSecure[2775:907] Unable to connect to server. Check xmppStream.hostName"

please help .... thanks in advance

**Comment by meflyup** [comment]
I have this problem on ios simulator ,and I think it's because it failed when trying to getting a certification from the server, so I reset the simulator,and roload the app ,re-login, and then it workd fine.
wish it help you 
regards.
