### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by VasuLaroiya** [ChatSecure/ChatSecure-iOS#227]
I cannot get this working on xcode 6. I get the error 

diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

Please help!

**Comment by MVakas** [comment]
I had the same error. I moved my project from root directory to Documents and now it’s working fine.
