### ISSUE TITLE
error while Submodule init from git using - git submodule update --init --recursive

### ISSUE THREAD

**Issue by jitenbansi** [ChatSecure/ChatSecure-iOS#228]
Hi, i tried new version of ChatSecure, but while downloading  submodules with 

$ git submodule update --init --recursive 

 i get this error, Please resolve 

Checking connectivity... done.
Submodule path 'Submodules/iOS-Screenshot-Automater': checked out '2c0754806538484ea0058a2417d3e8add92c0fe3'
Submodule 'tuneup_js' (git://github.com/alexvollmer/tuneup_js/) registered for path 'tuneup_js'
Cloning into 'tuneup_js'...
remote: Counting objects: 745, done.
remote: Total 745 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (745/745), 287.93 KiB | 83.00 KiB/s, done.
Resolving deltas: 100% (402/402), done.
Checking connectivity... done.
Submodule path 'Submodules/iOS-Screenshot-Automater/tuneup_js': checked out '6b92e27aa4948f291a3f0f9455be1c2c081872ff'
Failed to recurse into submodule path 'Submodules/XMPPFramework

thanks in advance

**Comment by Elnna** [comment]
@ chrisballinger .your advice fix my error!thanks very much!
