### ISSUE TITLE
error

### ISSUE THREAD

**Issue by XiaoWu123** [ChatSecure/ChatSecure-iOS#233]
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by MVakas** [comment]
I’m having the same issue. I’m running .xcworkspace but that doesn’t help.

**Comment by MVakas** [comment]
I moved my project from root directory to Documents and the error is gone.
