### ISSUE TITLE
Can't compile (JSQSystemSoundPlayer playSoundWithName:extension not declared)

### ISSUE THREAD

**Issue by roelvanhoof** [ChatSecure/ChatSecure-iOS#257]
After successfully following the installation instructions I am getting the error below. The installation worked as expected, gitmodules downloaded, pods installed, build-all scripts ran, opened the .xcworkspace.

There was one thing I didn't do but I don't know if this problem is related to that, which is 'add the public signing keys for OpenSSL, GnuPG, libevent, and libotr', i just downloaded and installed the GPGTools.

The error I am getting is this, it happens halfway through the compile in xcode.

/Projects/ChatSecure-iOS/Pods/JSQMessagesViewController/JSQMessagesViewController/Categories/JSQSystemSoundPlayer+JSQMessages.m:29:42: No visible @interface for 'JSQSystemSoundPlayer' declares the selector 'playSoundWithName:extension:'

When I look in xcode at the pods that are installed I do see the JSQSystemSoundPlayer pod.

**Comment by Ricardo1980** [comment]
I'm using the last pod version from here:
http://cocoapods.org/?q=JSMessagesViewController

4.0.4

And I see that problem.

**Comment by ngoclt** [comment]
@Ricardo1980 : You should use the latest version to fix this issue. Check this link to know how:
http://guides.cocoapods.org/using/the-podfile.html#specifying-pod-versions

PS: I think it's better to post these kinds of question to Stackoverflow instead of here.

**Comment by Ricardo1980** [comment]
Yes. You are right in both replies. Thanks a lot :)

Enviado desde mi iPhone.

**Comment by jault3** [comment]
@ngoclt the `latest` version of JSMessagesViewController is version 4.0.4. So regardless if you are using the 'latest' version as you suggested or not the issue still exists when using cocoapods. Specifying version numbers allows you to freeze versions so you do not run into issues such as this one. If a fix exists, it would be nice to get a new version pushed to cocoapods.

**Comment by ngoclt** [comment]
@jault3 : Make a double check. I'm pretty sure the latest version is not, it's 6.1.3
I saw that there are 2 sources on Cocoapods: *JSQMessagesViewController* (6.1.3) and *JSMessagesViewController* (4.0.4). 

Use _JSQMessagesViewController_
>pod 'JSQMessagesViewController'

**Comment by jault3** [comment]
I am aware there are two sources. When you rename a github repo, cocoapods does not handle this very nicely. The owner of the project renamed the library. He added a Q. If you use the old version, the "latest" is 4.0.4 which is an old and unsupported library. This old library relies on a new and up to date dependency (JSQSystemSoundPlayer) which had its method names changed. All I was saying is that it is unfortunate for those who were unaware that the library got renamed. Now they find themselves multiple iterations behind and require a complete refactor of their application to get it working again. But I guess that's what happens when you let you app sit dormant for too long.

**Comment by chrisballinger** [comment]
We've been keeping up to date with JSQ

**Comment by PickMe** [comment]
Hi,
i experienced the same problem, although i don't use cocapods (i'm new to programming swift, too complicated for me).
What I did is to rename the following in JSQSystemSoundPlayer.h:

//- (void)playSoundWithFilename:(NSString *)filename
//                fileExtension:(NSString *)fileExtension
//                   completion:(JSQSystemSoundPlayerCompletionBlock)completionBlock;

to following i found in an old version of the file:

- (void)playSoundWithFilename:(NSString *)filename fileExtension:(NSString *)fileExtension;

and

//- (void)playAlertSoundWithFilename:(NSString *)filename fileExtension:(NSString *)fileExtension completion:(JSQSystemSoundPlayerCompletionBlock)completionBlock;

to following i found in an old version of the file:

- (void)playAlertSoundWithFilename:(NSString *)filename fileExtension:(NSString *)fileExtension;

**Comment by mohonish** [comment]
Solution by @PickMe worked for me. Thanks! 
I'm using Swift 1.2 and XCode 6.3.2

**Comment by dong** [comment]
Thanks @ngoclt . That works for me.
