### ISSUE TITLE
Facing Problem While compiling the code with Xcode6.1

### ISSUE THREAD

**Issue by singh79** [ChatSecure/ChatSecure-iOS#258]
Subsequently getting following errors-
1) 1st error tor_cpaproxy.h file not found
2)JSQSystemSoundPlayer+JSQMessages.h no visible @interface for JSQSystemSoundPlayer
3) /usr/include/dns.h file not found
4) XMPPFramework Not found ….
5) ld: library not found for -lcrypto
6) ld: library not found for -lcurve25519_donna
clang: error: linker command failed with exit code 1 (use -v to see invocation)
I feel some script is not getting executed or any dependency is not getting downloaded, Please provide some guidelines and help me to compile the code.

Thanks in advance.
Subodh

**Comment by marcelosantoro** [comment]
cd Submodules/CPAProxy/
rm -rf CPAProxyDependencies

cd scripts/
rm -rf build
rm -rf built

vi build-openssl.sh
#after set -e

add: 
OPENSSL_VERSION="1.0.2b"

Save the File and run ./build-all.sh 

Worked for me.

**Comment by siliconprime-ninhvo** [comment]
It does not work for me

**Comment by anjum-vervesys** [comment]
It does not worked for me. @marcelosantoro .
@chuquangbao I am getting same issue.
@chrisballinger can you please elaborate more what do you mean by delete dependencies? from pods section i should delete and than try to add?

**Comment by marconealberto** [comment]
this didn't work for me either. Any other solution?

**Comment by marconealberto** [comment]
Ok my problem was that the 2 variables **TOR_VERSION** and **TOPDIR** were empty in the **build-tor.sh** . I had to manually set them.

**Comment by anjum-vervesys** [comment]
@marcelosantoro didn't get you what do you mean? is it going to work now? i am facing this error. "tor_cpaproxy.h' file not found". Any solution for this? i have followed above steps but didn't work for me. Can you please elaborate with proper steps? It would be great help.

**Comment by anjum-vervesys** [comment]
@marconealberto, what values did you set for TOR_VERSION and TOPDIR in build-tor.sh file.

**Comment by marconealberto** [comment]
forget what I wrote before. The solution from @marcelosantoro worked but I had to put the SSL version to

OPENSSL_VERSION="1.0.2d"

because that's the new file for the sources (https://www.openssl.org/source/ )

**Comment by anjum-vervesys** [comment]
@marconealberto  i have also tried with this and also made changes what you have mentioned "OPENSSL_VERSION="1.0.2d""

but still its not working. i am getting this error.

No iOS SDK specified. Using the only one available: 8.3
Building architectures: i386 x86_64 armv7 armv7s arm64
Building libraries: openssl libevent tor
./build-all.sh: line 71: cd: /Volumes/XXXX/XXXX: No such file or directory

@marconealberto can you please have a look at this.

**Comment by khawar-usman** [comment]
bash ./Submodules/CPAProxy/scripts/build-all.sh
No iOS SDK specified. Using the only one available: 8.4
Building architectures: i386 x86_64 armv7 armv7s arm64
Building libraries: openssl libevent tor
mkdir: /Users/maryamrabbi/Documents/Contents/ChatSecure-iOS/ChatSecure-iOS/Submodules/CPAProxy/scripts/built/i386/include/sys/: File exists
Building openssl for i386...
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.


i am still having this issue, can anyone of you let me know how to fix it?

@marconealberto  did you fix it already?

**Comment by khawar-usman** [comment]
I just checked, the OPENSSL_VERSION="1.0.2a" is in build-all.sh file
So i think, its already set to latest version, not sure why same error?

**Comment by Arabrellaxy** [comment]
@marcelosantoro  I have changed the OPENSSL_VERSION value to 1.0.2d,but I still couldn't build this project,it said that "tor_cpaproxy.h" can't be find,how can I solve this problem,please help me with that.Thank you very much.

**Comment by Arabrellaxy** [comment]
@anjum-vervesys  Have you solved your problem?I come cross the same problem with you.If you solved this problem,tell me the method  please.Thank you.

**Comment by anjum-vervesys** [comment]
@Arabrellaxy no i am not able to solve the issue i am still searching for solution. If you get any idea please tell me. Thanks

**Comment by anjum-vervesys** [comment]
@marconealberto 
It still gives me error after changing "OPENSSL_VERSION='1.0.2d'"

./build-all.sh: line 73: cd: /Volumes/Data_HD/USER: No such file or directory

@Arabrellaxy i think there may be an issue with build-all.sh i have opened that file with TextEdit and checked line there is issue the line says "cd ${BUILD_DIR}" didn't get what to do now

**Comment by Arabrellaxy** [comment]
@anjum-vervesys  I don't know what to do too.I'm still finding the solutions.Will inform you if I solved this.You inform me too please if you have any idea.Thank you.

**Comment by anjum-vervesys** [comment]
@Arabrellaxy  MAKE SURE YOUR ANY FOLDER NAME OR FOLDER PATH SHOULD NOT INCLUDE SPACE…? and followed the above steps 

cd Submodules/CPAProxy/
rm -rf CPAProxyDependencies

cd scripts/
rm -rf build
rm -rf built

vi build-openssl.sh
#after set -e

add: 
OPENSSL_VERSION="1.0.2b"

Save the File and run ./build-all.sh

 than i have try to build the processes its showing me now another issue.

tar: Unrecognized archive format
tar: Error exit delayed from previous errors.


I think i have to pull new fresh code in another folder path. Make sure some times we have to use sudo. Also please you try may be we reach the solution.

**Comment by anjum-vervesys** [comment]
@Arabrellaxy have you resolved the issue? are you able to work with the code? i am still not getting any resolution.

**Comment by Arabrellaxy** [comment]
@anjum-vervesys  I havn't solved yet.Any idea from you?

**Comment by Arabrellaxy** [comment]
@anjum-vervesys  It seems that my project has been built successfully.

**Comment by rajeshm20** [comment]
#!/bin/bash
set -e

# Download source
if [ ! -e "openssl-${OPENSSL_VERSION}.tar.gz" ]; then
  curl -O "https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz"  --retry 5
fi

# Extract source
rm -rf "openssl-${OPENSSL_VERSION}"
tar zxf "openssl-${OPENSSL_VERSION}.tar.gz"

# Build
pushd "openssl-${OPENSSL_VERSION}"

        if [ "${ARCH}" == "i386" ] || [ "${ARCH}" == "x86_64" ]; then
                if [ "${ARCH}" == "x86_64" ]; then
                        EXTRA_CONFIG="darwin64-x86_64-cc enable-ec_nistp_64_gcc_128"
                else
                        EXTRA_CONFIG="darwin-i386-cc"
-- INSERT --
 
/*what we have to do after above step in terminal */

**Comment by marcelosantoro** [comment]
Try to compile again !!!

Here it worked !!!

Best Regards.
Marcelo Santoro

**Comment by rajeshm20** [comment]
still got the same error "tor_cpaproxy.h" file not found....

**Comment by RMK19** [comment]
@marcelosantoro  What values did you set for TOPDIR in build-tor.sh file.

**Comment by jgrover** [comment]
I got this working.  You have to make sure the OPENSSL_VERSION value in build-openssl.sh matches what is currently available on http://openssl.org/source. Looks like it's currently up to "1.0.2f", so make sure to use that version in your build-openssl.sh
