### ISSUE TITLE
Unrecognized archive format

### ISSUE THREAD

**Issue by hydex86** [ChatSecure/ChatSecure-iOS#259]
I'm trying to setup the project and test it, but I'm getting an error trying to build submodules. This is what I did:

$ gem install cocoapods

$ git clone https://github.com/chrisballinger/ChatSecure-iOS.git
$ cd ChatSecure-iOS/
$ git submodule update --init --recursive

Then I tried this step:

$ bash ./Submodules/CPAProxy/scripts/build-all.sh

But I got an error:

 /usr/local/bin/ginstall -c -m 644  event2/buffer.h event2/buffer_compat.h event2/bufferevent.h event2/bufferevent_compat.h event2/bufferevent_ssl.h event2/bufferevent_struct.h event2/dns.h event2/dns_compat.h event2/dns_struct.h event2/event.h event2/event_compat.h event2/event_struct.h event2/http.h event2/http_compat.h event2/http_struct.h event2/keyvalq_struct.h event2/listener.h event2/rpc.h event2/rpc_compat.h event2/rpc_struct.h event2/tag.h event2/tag_compat.h event2/thread.h event2/util.h '/Users/dani/Documents/ChatSecure-iOS/Submodules/CPAProxy/scripts/build/iPhoneSimulator-8.0-i386/include/event2'
 /usr/local/bin/gmkdir -p '/Users/dani/Documents/ChatSecure-iOS/Submodules/CPAProxy/scripts/build/iPhoneSimulator-8.0-i386/include'
 /usr/local/bin/gmkdir -p '/Users/dani/Documents/ChatSecure-iOS/Submodules/CPAProxy/scripts/build/iPhoneSimulator-8.0-i386/include/event2'
 /usr/local/bin/ginstall -c -m 644  ./event2/event-config.h '/Users/dani/Documents/ChatSecure-iOS/Submodules/CPAProxy/scripts/build/iPhoneSimulator-8.0-i386/include/event2'
Making install in sample
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for`install-data-am'.
Making install in test
/Applications/Xcode.app/Contents/Developer/usr/bin/make  install-am
make[4]: Nothing to be done for `install-exec-am'.
make[4]: Nothing to be done for`install-data-am'.
~/Documents/ChatSecure-iOS/Submodules/CPAProxy/scripts/build
mkdir: /Users/dani/Documents/ChatSecure-iOS/Submodules/CPAProxy/scripts/built/i386/include/sys/: File exists
Building tor for i386...
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.

Then I tried next step:
$ bash ./Submodules/OTRKit/build-all.sh 

And I got: 
Building libgpg-error...
sh: build-libgpg-error.sh: No such file or directory
Building libgcrypt...
sh: build-libgcrypt.sh: No such file or directory
Building libotr...
sh: build-libotr.sh: No such file or directory

Did I do something wrong?

**Comment by JoeTog** [comment]
d

**Comment by JoeTog** [comment]
Building tor for i386...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0curl: (7) Failed to connect to dist.torproject.org port 443: Operation timed out

I cannot solve this problem , Is there any one can help me? thanks a lot

**Comment by chrisballinger** [comment]
Tor may be blocked in your region.

**Comment by JoeTog** [comment]
how to open it? and where

**Comment by JoeTog** [comment]
how open it or where?

**Comment by skumarm** [comment]
> since the tor version mentioned is 0.3.0.13 version which is moved to archive folder
> **manually download tor-0.3.0.13.tar from the following link**
> 
> > [download Archived file](https://archive.torproject.org/tor-package-archive/tor-0.3.0.13.tar.gz)
> 
> then copy the file into following directory
> 
> > Submodules/CPAProxy/scripts/build
> 
> then run the build file
> 
> **it solved for me** :) :)

This fixed my issue. Thanks alot...

**Comment by NrmeenTomoum** [comment]
I can't download this file ! @skumarm
