### ISSUE TITLE
Project integration 

### ISSUE THREAD

**Issue by astrokin** [ChatSecure/ChatSecure-iOS#262]
What is the best way to integrate part or all ChatSecure-iOS project functionality into my own xcodeproj?
Licensing question is clear morels. I'm interesting in deeper technical details. 
May be some document describes the installation process like this: 
https://github.com/RestKit/RestKit/wiki/Installing-RestKit-v0.20.x-as-a-Git-Submodule
Or just a few tells.
Thanks for help in advance.

**Comment by aadil031** [comment]
@chrisballinger i know this is a very old thread, but just wanna confirm is it possible now to use ChatSecure in other apps as module?
