### ISSUE TITLE
Server aborted the SSL handshake

### ISSUE THREAD

**Issue by hardikdevios** [ChatSecure/ChatSecure-iOS#268]
bash ./Submodules/CPAProxy/scripts/build-all.sh
No iOS SDK specified. Using the only one available: 8.1
Building architectures: i386 x86_64 armv7 armv7s arm64
Building libraries: openssl libevent tor
Building openssl for i386...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:07 --:--:--     0curl: (35) Server aborted the SSL handshake

**Comment by rajeshm20** [comment]
i had a same issue.... there  any certain downtime for that server? if so , when will we can run update?
