### ISSUE TITLE
How to verify contacts with Fingerprint

### ISSUE THREAD

**Issue by stoyan-simov-vox** [ChatSecure/ChatSecure-iOS#277]
Hello,

My aim is to verify contacts with fingerprints. What I know about fingerprints is that this is some shorten part of hashed privateKey and is used for verification between two parties to be sure what they are talking to.

I installed ChatSecure app and look to find the process of getting this fingerprints.

Lets suppose we have user A@xmpp.product.me and user @"B@xmpp.product.me"
and we want to get their fingerprint for verification.
What I understand is needed for getting this from ChatSecure:

1. Initiate OTR Connection -  //Start OTR
            [[OTRKit sharedInstance] initiateEncryptionWithUsername:@"B@xmpp.product.me" accountName:@"A@xmpp.product.me" protocol:@"xmpp"];

2. Here should be called methods for generating private keys:
willStartGeneratingPrivateKeyForAccountName
	didFinishGeneratingPrivateKeyForAccountName
	showFingerprintConfirmationForTheirHash
 
3. After establishing otr - get fingerprints with:
 [[OTRKit sharedInstance] fingerprintForAccountName:@"A@xmpp.product.me" protocol:@"xmpp" completion:^(NSString *ourFingerprintString) {
        
        [[OTRKit sharedInstance] activeFingerprintForUsername:@"B@xmpp.product.me"  accountName:@"A@xmpp.product.me" protocol:@"xmpp" completion:^(NSString *theirFingerprintString)

Is tehre something else that should be done to get fingerprints, because right now fingerprints are (null) with this process. May be I am missing something?

Should accounts A and B be connected and what methods are needed to do so?

Thanks in advance

**Comment by chrisballinger** [comment]
Track upstream in OTRKit
