### ISSUE TITLE
Failed to connect to XMPP server.

### ISSUE THREAD

**Issue by naveedh** [ChatSecure/ChatSecure-iOS#290]
I am using openfire.

At my first attempt I was able to login and even search users. now I keep getting following error.

Error!
Failed to connect to XMPP server. Please check your login credentials and internet connection and try again.

info

org.chatsecure.ChatSecure: <failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl"> <not-authorized/></failure>

ChatSecure is a great app and I would like to use it over IM. I am currently using IM with out any issue. but I would like to switch over to ChatSecure.

**Comment by davidchiles** [comment]
It's really hard to debug this without the XMPP log statements. Do you have those or a test account we could try?

**Comment by naveedh** [comment]
Thanks for your response, is there a way I can share login details to you ?

**Comment by davidchiles** [comment]
Thank you for sending credentials. So the error is happening during SASL authentication. [XMPPFramework](https://github.com/robbiehanson/XMPPFramework) is choosing to use `DIGEST-MD5`. I receive the challenge, send a response and then receive:
 `<failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><not-authorized/></failure>`
I was able to get it to work on Adium so I'm not sure what is going wrong in ChatSecure.

**Comment by naveedh** [comment]
David, is there any logs or information I can send to fix this issue? If you want I can send you my server login details.

I am using Openfire latest version on CentOS 6.5 VPS.

**Comment by naveedh** [comment]
Good day David,

Finally manager to get the issue fix, problem was it does not take user by host id but what is register in AD DC.

You have a GREAT APP, but now what I am facing the problem like many other is notification updates (Push notifications). After all this days of troubleshooting/pain full google search, just to use chat secure, I endup with no push notifications. 

I have read your article as to why this feature is disable, but how does IM+, Watsapp and many more such app are running ?

If you made this app paid I and other are willing to pay with this feature enable.

Please email me, currently I switch back to IM+.


Regards and thanks for such a great app,

Naveed Hasan
