### ISSUE TITLE
Apple Mach-O Linker Error

### ISSUE THREAD

**Issue by nickloyal** [ChatSecure/ChatSecure-iOS#292]
This is the error I am getting while trying to build:

ld: warning: directory not found for option '-L/Users/nlctrl/Documents/ChatSecure-iOS/Pods/XMPPFramework/Vendor/libidn'
ld: file not found: /Users/nlctrl/Library/Developer/Xcode/DerivedData/ChatSecure-gbomfgddxbtwsiecjklyylhajqbv/Build/Products/Debug-iphoneos/ChatSecure.app/ChatSecure
clang: error: linker command failed with exit code 1 (use -v to see invocation)

![screen shot 2014-12-30 at 4 18 59 am](https://cloud.githubusercontent.com/assets/7691646/5577257/60037e7c-8fdb-11e4-9a3b-c4e95d5b778f.png)

**Comment by chrisballinger** [comment]
Did you follow the [build instructions](https://github.com/ChatSecure/ChatSecure-iOS#build-instructions)?

**Comment by nickloyal** [comment]
Yes I did it's still causing the same issue.  Rest of the issues are fixed this is the last thing thats still causing issues deploying.

**Comment by Catalyst085** [comment]
I also am facing the same problem, followed the instruction still :(

**Comment by ghpo** [comment]
libevent 
build-all
/Users/Administrador/Downloads/ChatSecure-iOS/Submodules/CPAProxy/CPAProxy/CPAThread.m:9:9: 'tor_cpaproxy.h' file not found

someone? help please
