### ISSUE TITLE
My code is running on simulator but not on device why?

### ISSUE THREAD

**Issue by WarisShams** [ChatSecure/ChatSecure-iOS#296]
Hi everyone,
I want to use ChatSecure in my iOS app for chatting, so i downloaded the project from https://github.com/ChatSecure/ChatSecure-iOS/tree/master . But after resolving all things when i run it on simulator its working fine and running but when i tried to run this on iOS device it giving errors  like shown in image.
![screen shot 2015-01-09 at 1 06 16 pm](https://cloud.githubusercontent.com/assets/8637736/5678524/4606a084-9815-11e4-8fcd-eb51d383b77a.png)

Kindly help to resolve these issues. Or tell me the way to use this in my app. 
Thanks in advance.

**Comment by vitalyster** [comment]
You have OTRkit compiled for x86 but not for arm

**Comment by WarisShams** [comment]
is It valid for 32 and 64 bit both?
