### ISSUE TITLE
I'm getting errors using JSQSystemSoundPlayer

### ISSUE THREAD

**Issue by edwjon** [ChatSecure/ChatSecure-iOS#298]
I'm getting these errors and i don't now hot to fix it...
![captura de pantalla 2015-01-16 a las 10 08 15 a m](https://cloud.githubusercontent.com/assets/7462469/5777809/129891d2-9d68-11e4-9057-4727b74e2027.png)

Can someone help me???

**Comment by chrisballinger** [comment]
Verify that your Cocoapods installation is up to date

**Comment by edwjon** [comment]
Yeah, i have the latest version of cocoapods, but i still getting the error!!
What more can i do???
Thanks!!

**Comment by argoel** [comment]
Was this resolved? I am facing the exact same errors. I believe it's because I updated to the newest version of JSQMessageSound?
