### ISSUE TITLE
Ability to choose different fonts, or at least font size

### ISSUE THREAD

**Issue by ghost** [ChatSecure/ChatSecure-iOS#30]
The default font size is huge (on an iPhone 3GS, using iOS 5.1.1). It would be great if I could modify at least the text size, or if I could choose from a list of fonts. (Since the default one is outright terrible.)

**Comment by ioscanner** [comment]
Has this been added?  On the Iphone XS Max the font is very small making it hard to read on the main screen.  I see no way to modify the text size.  It seems the chat window when in a chat is dynamic and adjusts based on the default phone font settings, but not the main screen.
