### ISSUE TITLE
Can this be integrated into a larger application?

### ISSUE THREAD

**Issue by ericgross** [ChatSecure/ChatSecure-iOS#301]
I already have an iOS app which I'd like to add this to - can I add this project to an existing app rather than run it as its own app?

If so, how would you do that? I am trying to use cocoapods as much as possible.

I have already integrated JSQMessagingViewController but trying to add in XMPP on my own seems silly with this already done by this fine project.

**Comment by chrisballinger** [comment]
Not yet.. but soon
