### ISSUE TITLE
Typing bar in the middle

### ISSUE THREAD

**Issue by rosagp** [ChatSecure/ChatSecure-iOS#306]
![img_3947](https://cloud.githubusercontent.com/assets/4604279/5840537/43438e86-a164-11e4-97fb-6e2c8226a020.PNG)
![img_3948](https://cloud.githubusercontent.com/assets/4604279/5840538/4617d414-a164-11e4-9a5e-0acff91a4c1a.PNG)

Shouldn't the typing bar be at the bottom? When I tap in the box the keyboard comes up but it would look nicer if the bar was at the bottom until the keyboard comes up. I took screenshots. Let me know if it doesn't come through.

**Comment by chrisballinger** [comment]
JSQ bug
