### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by rosagp** [ChatSecure/ChatSecure-iOS#307]
![img_3953](https://cloud.githubusercontent.com/assets/4604279/5840720/b65f981e-a165-11e4-9097-e9a62b1ec665.PNG)
![img_3954](https://cloud.githubusercontent.com/assets/4604279/5840725/ba2131f6-a165-11e4-9732-cddbd084e663.PNG)

When I open the app and go to settings I can't log in even though I was able to earlier. The compose icon is greyed out and when I go to settings, then my google account and then tap on Log In, nothing happens. I tried just texting someone I already texted before and I got the error message as seen in the screen shot. I've tried quitting the app and opening it again and same thing happens.

**Comment by chrisballinger** [comment]
Fortunately we've fixed this usability issue in the develop branch. If
you're not logged in it will prompt you to connect instead of showing a
cryptic error message.

**Comment by rosagp** [comment]
It has not prompted me to connect. What else should I do to connect?

**Comment by chrisballinger** [comment]
Oh sorry, that feature isn't shipping in any betas yet.
