### ISSUE TITLE
Stability and encrypted chat initiation

### ISSUE THREAD

**Issue by ctulhoo** [ChatSecure/ChatSecure-iOS#309]
Hello!

I am using latest apps and iOS (3.0 and 8.1.2 on ip6) via cellular mainly, but wifi possible too at home.
My issues that logging is ok for several servers jabberpl.org, gmail, dukgo.com, jabber.calyxinstitute.org (was trying to figure the best server) for the first opening of app. When the app goes to background, the connecting can be problematic sometimes. Need to close app manually and start again.

Can you please suggest best possible and safest settings for such noob as me :)

Next big problem is that with my friend(he is using the same versions of iOS and app). When using gmail account, than its possible to start encrypted chat. As for the other servers when i push initiate encrypted chat nothing happens. Can you please help solve such issues?

appreciate any help,
cheers

**Comment by ctulhoo** [comment]
I believe that these are critical issues that need to be addressed first.
btw, i applied for beta test, can you please approve my account under same name? thanks!

**Comment by chrisballinger** [comment]
This should be resolved in the upcoming v3.2 release
