### ISSUE TITLE
OTRXMPPErrorDomain

### ISSUE THREAD

**Issue by mstekker** [ChatSecure/ChatSecure-iOS#310]
Hi,

Trying to connect to OpenFire I get error:
OTRXMMPErrorDomain : The operation couldn't be completed
(OTRXMMPErrorDomain error 1.)

Does anybody know what I am doing wrong?
Openfire 3.9.3, newest iOS ChatSecure client,

Does chatsecure work with OpenFire?

Thanks!

Mart

**Comment by dafydd2277** [comment]
Getting the same error trying to connect to Facebook.

**Comment by dafydd2277** [comment]
Troubleshooting: I had actually installed ChatSecure before installing FB Messenger. So, I uninstalled both and tried various combinations of reinstalling. No change in behavior. I'm still getting the same message as above.

**Comment by jsponz** [comment]
Any progress on this? Any answer?

**Comment by mstekker** [comment]
No progress - sorry

**Comment by chrisballinger** [comment]
It won't work because the server is saying you aren't authorized.
