### ISSUE TITLE
send / recieve images /ios

### ISSUE THREAD

**Issue by mstekker** [ChatSecure/ChatSecure-iOS#311]
Hi,

Is there an option to send / receive images in chatsecure for iOS?

Thanks,

Mart

**Comment by davidchiles** [comment]
We're currently working on this in https://github.com/ChatSecure/ChatSecure-iOS/tree/otrdata. Still early days but the hope is you'll be able to media between ChatSecure iOS and ChatSecure android.

**Comment by mstekker** [comment]
Would be very cool! Thx!
