### ISSUE TITLE
Message coming in unordered sequence if APP i closed and reopened 

### ISSUE THREAD

**Issue by hardikdevios** [ChatSecure/ChatSecure-iOS#316]
Ok, first of all i have successfully integrated this in Our application , Thanks for this awesome support.
Now my issue is regarding message sequence if app is in totally closed and user 1 send to user 2, so user 2 is offline and app is closed .. now User 1 sends 2 3 messages after that user 2 open the app  and goes into chat screen the message is not display in order.. it display in between of Newer and older message .. does anywhere i can mange this ? does any timezone issue ? Thanks in Advanced..

**Comment by chrisballinger** [comment]
Is this still an issue? We may have resolved this in the latest releases
