### ISSUE TITLE
getting error while trying to execute the project

### ISSUE THREAD

**Issue by rptwsthi** [ChatSecure/ChatSecure-iOS#317]
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by MVakas** [comment]
Hi I’m getting the same error. Any solution?

**Comment by MVakas** [comment]
Hi
I solved the issue by moving my project from root directory to Documents directory.
