### ISSUE TITLE
QR Fingerprint Recognition

### ISSUE THREAD

**Issue by Miserlou** [ChatSecure/ChatSecure-iOS#32]
I suggest a schema for qr codes to verify fprints:

otr://username@protocol/f1ng3prpr1nth4sh1sh

Which would allow app-agnostic fingerprint recognition.

X-Post to Gibberlist/OTR-dev?
R

**Comment by chrisballinger** [comment]
support in develop branch

**Comment by Miserlou** [comment]
Woah, really? What did the schema end up being?

**Comment by chrisballinger** [comment]
https://github.com/robbiehanson/XMPPFramework/blob/master/Extensions/XEP-0147/XMPPURI.h

XMPP URIs + the `otr-fingerprint=DEADBEEF` key
