### ISSUE TITLE
I cannot seem to add a chat buddy

### ISSUE THREAD

**Issue by RebeccaSeven** [ChatSecure/ChatSecure-iOS#320]
When I go to add my husband on so I can chat with him securely it seems to connect our accounts together and we end up chatting with our own account because my username was added to his and vice a versa when we try to do at each other as buddies 
He has the iPhone six through Verizon I have the iPhone six through AT&T

**Comment by chrisballinger** [comment]
We will be adding a much improved UI for inviting friends in v3.2
