### ISSUE TITLE
Can't check out the submodule

### ISSUE THREAD

**Issue by bagusflyer** [ChatSecure/ChatSecure-iOS#323]
Hi, I got the following error when I'm trying to run:

> git submodule update --init --recursive

> Warning: Permanently added 'github.com,192.30.252.128' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Can anybody help? How can I download the source code? Thanks

**Comment by vitalyster** [comment]
Add your public key here - https://github.com/settings/ssh
Or replace git://... links with https://.. in .gitmodules

**Comment by bagusflyer** [comment]
It works after I generate the public key. Thanks
