### ISSUE TITLE
Allow for messages to be received when app is closed

### ISSUE THREAD

**Issue by gonzalezb** [ChatSecure/ChatSecure-iOS#325]
Or at least when the app is in the background but closed it is possible because other popular instant messengers do it on iOS this app will continue to be a joke until you fix the problem of the app has to be open to even receive messages.

**Comment by arisbakri** [comment]
I agree toward's gonzalezb's statement

**Comment by chrisballinger** [comment]
This is much more difficult to achieve than simply adding the feature to
the client software. If it was, I would have done it years ago. Adding push
support requires us to run servers and will not work with any arbitrary
XMPP server. Other apps have solved this by running a man-in-the-middle
server that acts as a thin XMPP client, but it means they also have
complete access to your communications and XMPP login credentials. This is
an unacceptable design.

I do have plans for a way to solve this problem in a way that preserves
your privacy and we will be implementing them over the next year.

**Comment by ccp999** [comment]
Could you briefly discuss your solution to this problem?  We may be able to contribute.

**Comment by chrisballinger** [comment]
duplicate of #367
