### ISSUE TITLE
Can not login in xmpp

### ISSUE THREAD

**Issue by vonnyfly** [ChatSecure/ChatSecure-iOS#329]
I use other xmpp client which can login in. The only different of config is using old-style SSL. However, ChatSecure has not this item.

**Comment by gallygaskins** [comment]
I have installed ChatSecure and verified that the Facebook Settings allows it to connect. I select New Account/Connect to Existing Account/Facebook, then either Log In or Connect Facebook (same outcome for both). I get an error message 'Failed to connect to XMPP server. Please check credentials...', and the Info for this is 'OTRXMPPErrorDomain: The operation couldn't be completed. (OTRXMPPErrorDomain error 1.)' The new entry in the Accounts list is '(null)@chat.facebook.com', though it never becomes available. This happens on my 3-gen iPad running iOS 8.2 and my iPhone 4S running iOS 7.1.2

**Comment by jsponz** [comment]
Progress on this? Any answer?

**Comment by chrisballinger** [comment]
We no longer support old style SSL, sorry!
