### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by rosagp** [ChatSecure/ChatSecure-iOS#333]
When I tried to send audio, it crashed the app and when i tried to reopen the app, it crashed again. This happened twice. Then I just opened the app and forced quit it. Upon opening it again, it connected but then when I tried to resume my chat, it crashed. I tried to reopen my app a few more times but same thing would happen, it would just crash. So I had to delete the app and reinstall it. Reports were sent each time. Also, audio was sent to me but I didn't receive it.

**Comment by chrisballinger** [comment]
We found the crash report, thanks!

**Comment by chrisballinger** [comment]
This seems to be an iOS 7 auto-layout bug.
