### ISSUE TITLE
Android issue

### ISSUE THREAD

**Issue by IgorMar** [ChatSecure/ChatSecure-iOS#336]
Hello,

I connected to the my IP PBX using your app on IOS successfully, but when I tried to connect using Android it's not work. My user in the PBX in following format : XXXX*XXX, when I try to connect using Android device, your app throw the star that located in the middle of username.

It is the bug in app?
Can you check it please?

Regards,

Igor

**Comment by davidchiles** [comment]
this seems like an issue for the [Android repo](https://github.com/guardianproject/ChatSecureAndroid)
