### ISSUE TITLE
Support for XEP-0280: Message Carbons

### ISSUE THREAD

**Issue by andersruneson** [ChatSecure/ChatSecure-iOS#337]
Currently ChatSecure cannot be used at the same time that another client is connected for the same account because the messages may not end up in ChatSecure but on the other client. 

Message Carbons makes all messages (both incoming and outgoing) end up on all clients.

http://xmpp.org/extensions/xep-0280.html

**Comment by davidchiles** [comment]
We've looked at Message Carbons before and there are a few things stopping us right now from implementing it.

1. Behavior during OTR conversation. Since there is no Multi-peer OTR sending an OTR message to another client would just show up as encrypted garbage.
2. Not much [server support](https://davidchiles.github.io/XEPper/)

I guess one thing we could do is enable it during unencrypted conversations and disable it during OTR sessions. But that's even more complexity 😊

**Comment by andersruneson** [comment]
Or maybe look into axolotl support.

**Comment by chrisballinger** [comment]
Axolotl support is on our roadmap, unfortunately it also won't work well with XMPP message carbons.

**Comment by iNPUTmice** [comment]
> I guess one thing we could do is enable it during unencrypted conversations and disable it during OTR sessions. But that's even more complexity

It really does not. You can mark a message as no-copy and the server will not carbon-copy that specific message

> Not much server support

There is support in prosody and ejabberd which right now are the most widespread servers anyway [citation needed]. And lack of server support is always a terrible argument. If the server developers where to choose what XEPs to implement based on client support you would never see any progress.

**Comment by davidchiles** [comment]
I didn't know about no-copy. That would make it a bit easier. 

I can work on setting up an XMPP server to test against in the future. We're always looking to implement more XEPs especially those already implemented in [XMPPFramework](https://github.com/robbiehanson/XMPPFramework) 😊

**Comment by d9h02f** [comment]
For people on iOS this is currently the only free XMPP client available, so regardless of whether or not they use encryption, I think it's really worth giving some priority to this (and https://github.com/ChatSecure/ChatSecure-iOS/issues/361 as well). Lack of support for these two XEPs (and the app disconnecting as soon as it's in the background) unfortunately makes ChatSecure not really work as a mobile XMPP client.

**Comment by chrisballinger** [comment]
@d9h02f We are actively working on push support to solve most of those pain points: https://github.com/chatsecure/chatsecure-push-ios

Those additional XEPs are definitely on the roadmap.

**Comment by d9h02f** [comment]
Great!

**Comment by chrisballinger** [comment]
XEP-0280 support is now in the develop branch

**Comment by laclaro** [comment]
I'm having problems receiving (and distributing) carbon copies to/from my ChatSecure 4.3.7 (139) on iOS 12. I guess it should definitively work nowadays, correct?

Other Clients are exchanging carbons normally: Gajim (Windows+Linux), Conversations (Android)

Best

Henning

**Comment by pd888** [comment]
I am using prosody server with carbons on and other clients (dino, adium) show the carbon messages however chat secure does not load previous messages when adding account. 

When loading server information on chatsecure app - carbons does not show as supported. 
Just confirming carbons are supported in chatsecure?
