### ISSUE TITLE
iOS 6

### ISSUE THREAD

**Issue by ccvca** [ChatSecure/ChatSecure-iOS#342]
I know, that this App currently need iOS 7, but it would be nice, if the latest iOS 6 Version would be also available. (https://support.apple.com/en-us/HT201377)

**Comment by chrisballinger** [comment]
Unfortunately we are more likely to go in the other direction and require iOS 8+ by the end of the year. Sorry!

**Comment by ccvca** [comment]
My idea was not, that the current Version is compatible with iOS6. My idea was, that the latest iOS6 compatible Version is availiable in the AppStore. If I undestand the article above wright, there is a possibility to upload old Versions in the AppStore for old iOS Versions.
