### ISSUE TITLE
Can't clone the source from git with all the dependencies

### ISSUE THREAD

**Issue by fspprasanna** [ChatSecure/ChatSecure-iOS#343]
I have followed the instruction and I am able to execute these two commands successfully(1.git clone https://github.com/ChatSecure/ChatSecure-iOS.git    2.cd ChatSecure-iOS/ ) from my terminal app in Mac Os and when I runn this third one(3.git submodule update --init --recursive) I am getting error in downloading submodules (error : Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:ChatSecure/CPAProxy.git' into submodule path 'Submodules/CPAProxy' failed) Can you please guide me to proceed further

**Comment by vitalyster** [comment]
You need to add your public key to Github account, or replace `git@github.com:orgname` to `https://github.com/orgname` links in `.gitmodules` file
