### ISSUE TITLE
tor_cpaproxy.h file not found

### ISSUE THREAD

**Issue by cosmobile** [ChatSecure/ChatSecure-iOS#345]
I followed step by step the guide, but I always obtain this error and I can't build the project.
What should I do?

**Comment by badalpub1991** [comment]
i got a same problem. have your problem solved ??

**Comment by Alaa-Eldin** [comment]
I have the same problem, any solution?

**Comment by badalpub1991** [comment]
I have solved this problem with just move all subroutine folders to project properly. (select option copy folder and create group)  subroutine->CPAproxy folder already contain this file (tor_cpaproxy.h). so just move folder again properly in your project.

**Comment by anjum-vervesys** [comment]
@badalpub1991 can you please elaborate more on that issue. I have also tried to solve this by "#258" but its still not working can you please help me to resolve this issue? It would be great help.

**Comment by badalpub1991** [comment]
@anjum-vervesys :- Yes obvesly. Actualy this problem is come because you have to drag and drop whole XMPP folder in your project. but inplace of drag and drop whole XMPP folder drag and drop one by one all folder which come in subroutine folder. On wiki XMPP mention that you need to drag and drop all the folder which are in  subroutine folder  one by one to your project. please try and say.

**Comment by anjum-vervesys** [comment]
@badalpub1991 do you have any idea what this steps exactly do? what to do?

Im following the steps to install ChatSecure-iOS, and i dont know how to continue in the following step:
"Install GPGTools and add the public signing keys for OpenSSL, GnuPG, libevent, and libotr. (TODO make these links to the keys)".

How can i do this? How can i add these public signing keys?

**Comment by badalpub1991** [comment]
@anjum-vervesys :- Have you refer this link ? it gives full description and also image . please follow step by step guid .
 http://support.gpgtools.org/kb/how-to/first-steps-where-do-i-start-where-do-i-begin-setup-gpgtools-create-a-new-key-your-first-encrypted-mail

**Comment by anjum-vervesys** [comment]
@badalpub1991  i have created but what to do? i dont know why its need to be done? is it required for chat secure?

and dont know why i am getting this error. Can you please guide me i am not finding any way to resolve this.
![screen shot 2015-08-04 at 5 52 20 pm](https://cloud.githubusercontent.com/assets/12491182/9060475/e3adf8b4-3ad1-11e5-826c-95ba372ff8b9.png)

**Comment by badalpub1991** [comment]
@anjum-vervesys :- are you working on chatsecure or impliment it in your own project ?

**Comment by anjum-vervesys** [comment]
@badalpub1991  i am trying to download the working code as mentioned steps.
Here https://github.com/ChatSecure/ChatSecure-iOS

**Comment by bktowett** [comment]
Same issue, I've tried the solutions above but none is working

**Comment by zainullah** [comment]
hello, this is how i fixed it
close Xcode
open the project folder > submodules > cpaproxy > scripts 

open build.sh with text editor
remove double quotes from version names and rename the versions to the latest available versions

example, TOR_VERSION=0.2.8-rpc

save and navigate to the build-all.sh directory
run this command  "./build.sh" 

once successful, run "pod update" in the root project directory

if you get reference errors after you build : 
refer to this link : https://github.com/ChatSecure/ChatSecure-iOS/issues/491

**Comment by JoeTog** [comment]
may I ask you to get this project's download address? I really cannot configure this project, I try to configure it for almost four days, but no result.

**Comment by ikyh** [comment]
@zainullah Hello... I did the same u said above. still I am getting the same error. Please help. Also after doing the steps said in README, still it gives pod install errors. please help

**Comment by E11iotAllSafe** [comment]
Guys please mind the tor version in build_tor.sh has been archived by tor on 20-11-2018. instead go to the file and change the curl's URL to "https://archive.torproject.org/tor-package-archive/tor-0.3.0.13.tar.gz"
