### ISSUE TITLE
Unbalanced KVO for numberOfConnectedProtocols

### ISSUE THREAD

**Issue by chrisballinger** [ChatSecure/ChatSecure-iOS#349]
Happens on viewWillDisappear for OTRConversationsViewController and OTRSettingsViewController. It's trying to remove an observer that's not registered. 

Worth investigating [KVOController](https://github.com/facebook/KVOController)?

**Comment by chrisballinger** [comment]
Still seeing this on 3.1.1. :(

**Comment by davidchiles** [comment]
Think I got them all :smile:

**Comment by davidchiles** [comment]
I think I got them all :smile:
