### ISSUE TITLE
iOS 8+ Cleanup

### ISSUE THREAD

**Issue by chrisballinger** [ChatSecure/ChatSecure-iOS#353]
When we change the minimum version supported to iOS 8, these are things that should be cleaned up:

- [ ] Remove custom language switcher in favor of system switcher
- [ ] Move to UIAlertController and remove UIAlertView/UIActionSheet
- [ ] Move conversation list and messages list to `UISplitViewController` for all device types

**Comment by RinoKRD** [comment]
Ни
