### ISSUE TITLE
Error installing gtm-http-fetcher

### ISSUE THREAD

**Issue by lawzhangqi** [ChatSecure/ChatSecure-iOS#356]
$ pod instill 

Installing gtm-http-fetcher (1.0.142)

[!] Error installing gtm-http-fetcher
[!] /usr/bin/svn export --non-interactive --trust-server-cert --force http://gtm-http-fetcher.googlecode.com/svn/trunk/ -r 142 /var/folders/4s/5frxk6c1369678k55tkq8qj40000gn/T/d20150607-2476-13jntb0

svn: E175002: Unable to connect to a repository at URL 'http://gtm-http-fetcher.googlecode.com/svn/trunk'

svn: E175002: OPTIONS of 'http://gtm-http-fetcher.googlecode.com/svn/trunk': could not connect to server (http://gtm-http-fetcher.googlecode.com)

**Comment by chunmingkong** [comment]
Did you have a solution to solve it? I caught in the same problem as well and i don't know how to deal with it with a perfect way.
