### ISSUE TITLE
New testing issues

### ISSUE THREAD

**Issue by rosagp** [ChatSecure/ChatSecure-iOS#357]
Here the recent issues that occurred when testing version 3.1.1 (downloaded from the app store):

-I tried logging on to Jabber (XMPP) a few times but kept getting an error message.
![Uploading IMG_5767.PNG…]()
![Uploading IMG_5768.PNG…]()

-I tried logging on to XMPP + Tor and when I tapped Log In, nothing happened. I tried an alternate route and just messaged someone and it says You are not connected Connect, tapped on it and then it went to the Log in page but still could not log in.

**Comment by rosagp** [comment]
![img_5767](https://cloud.githubusercontent.com/assets/4604279/8109220/90bf8a88-1023-11e5-9f72-613bf63dfd65.PNG)

![img_5768](https://cloud.githubusercontent.com/assets/4604279/8109209/8841a774-1023-11e5-9daa-5918245bc366.PNG)

**Comment by chrisballinger** [comment]
It looks like you didn't specify a server. A full JID looks like an email address e.g. username@example.com

**Comment by rosagp** [comment]
I tried rosa@dukgo.com and it didn't work either. I think maybe the password doesn't match? The error message I got said: OTRXMPPErrorDomain: The response provided by the client doesn't match the one we calculated. If it is the password issue, how do I retrieve it? There's no option to do so.

**Comment by rosagp** [comment]
The other issue I'm having is that after trying to use a different account and it didn't work, I went back trying to use the account that is stored. And then when I try to tap on "Log In" it doesn't work. I also tried sending a message to someone that I've already chatted with and it asks me to connect but when I try to do so, it won't log me in.
