### ISSUE TITLE
Every time got this issue. `YapDatabase/SQLCipher (from `Submodules/YapDatabase/YapDatabase.podspec`)` required by `Podfile`

### ISSUE THREAD

**Issue by ashishgupta301** [ChatSecure/ChatSecure-iOS#369]
When install pod then got this issue.

`YapDatabase/SQLCipher (from `Submodules/YapDatabase/YapDatabase.podspec`)` required by `Podfile`

**Comment by ashishgupta301** [comment]
Please give me some idea related to this issue.

**Comment by orta** [comment]
@ashishgupta301 I think you need to run `git submodule update --init --recursive`

**Comment by ashishgupta301** [comment]
When i am run git submodule update --init --recursive
then following problem are occur.

Submodule 'Submodules/CPAProxy' (git@github.com:ursachec/CPAProxy.git) registered for path 'Submodules/CPAProxy'
Submodule 'Submodules/ChatSecure-Metadata' (git@github.com:ChatSecure/ChatSecure-Metadata.git) registered for path 'Submodules/ChatSecure-Metadata'
Submodule 'Submodules/IOCipher' (git@github.com:ChatSecure/IOCipher-ObjC.git) registered for path 'Submodules/IOCipher'
Submodule 'Submodules/OTRKit' (git@github.com:ChatSecure/OTRKit.git) registered for path 'Submodules/OTRKit'
Submodule 'Submodules/OnionKit' (git@github.com:ChatSecure/OnionKit.git) registered for path 'Submodules/OnionKit'
Submodule 'Submodules/ProxyKit' (git@github.com:chrisballinger/ProxyKit.git) registered for path 'Submodules/ProxyKit'
Submodule 'Submodules/XMPPFramework' (git@github.com:ChatSecure/XMPPFramework.git) registered for path 'Submodules/XMPPFramework'
Submodule 'Submodules/YapDatabase' (git@github.com:chrisballinger/YapDatabase.git) registered for path 'Submodules/YapDatabase'
Cloning into 'Submodules/CPAProxy'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:ursachec/CPAProxy.git' into submodule path 'Submodules/CPAProxy' failed

**Comment by orta** [comment]
Did you check if the repo exists?

**Comment by chrisballinger** [comment]
Gotta add your SSH public key to GitHub

**Comment by jramirezmx** [comment]
Is it only the repository is possible solve this isssue? 
Only solve this I need, please !

**Comment by ashishgupta301** [comment]
@chrisballinger  Done using SSH public key to GitHub.

**Comment by jramirezmx** [comment]
Yes, use public key to Github, resolved my problem. Thanks

**Comment by ramchandaluri** [comment]
I have the same issue but I had added the ssh key

**Comment by pasha4uu** [comment]
when I'm running pod install getting this type error 
_**[!] No podspec found for YapDatabase in Submodules/YapDatabase/YapDatabase.podspec**_
even after adding the ssh key 
I found error will running : git submodule update --init --recursive
error: **Server does not allow request for unadvertised object 8073394acf5c540584f06a5e74c38eb3cd506572
Fetched in submodule path 'Submodules/YapDatabase', but it did not contain 8073394acf5c540584f06a5e74c38eb3cd506572. Direct fetching of that commit failed.**
any help Would be really Appreciated.....

**Comment by skarsad04** [comment]
> when I'm running pod install getting this type error
> _**[!] No podspec found for YapDatabase in Submodules/YapDatabase/YapDatabase.podspec**_
> even after adding the ssh key
> I found error will running : git submodule update --init --recursive
> error: **Server does not allow request for unadvertised object 8073394acf5c540584f06a5e74c38eb3cd506572 Fetched in submodule path 'Submodules/YapDatabase', but it did not contain 8073394acf5c540584f06a5e74c38eb3cd506572. Direct fetching of that commit failed.**
> any help Would be really Appreciated.....

Try to clone different branch :
git clone -b xcode-11 https://github.com/ChatSecure/ChatSecure-iOS.git

and follow below instruction 

$ cd ChatSecure-iOS/
$ git submodule update --init --recursive

Now you'll need to build the dependencies.

$ bash ./Submodules/CPAProxy/scripts/build-all.sh
$ bash ./Submodules/OTRKit/scripts/build-all.sh
$ pod repo update
$ pod install

Next you'll need to create your own version of environment-specific data. Make a copy of Secrets-template.plist as Secrets.plist:

$ cp OTRResources/Secrets-template.plist OTRResources/Secrets.plist


You'll need to manually change the Team ID under Project -> Targets -> ChatSecure -> Signing. The old .xcconfig method doesn't seem to work well anymore.

Open ChatSecure.xcworkspace in Xcode and build.
