### ISSUE TITLE
confirming state messaging fails

### ISSUE THREAD

**Issue by nespaona** [ChatSecure/ChatSecure-iOS#372]
to have a change in network 3g 4g, that very short period of time the messages are lost

**Comment by chrisballinger** [comment]
Our new support for 0198 should help fix that problem

**Comment by nespaona** [comment]
hello not if server configuration issue, but over 3g to 4g happens, or when I'm in flight mode and step back with lost data
Thank you

**Comment by nespaona** [comment]
when we can have that version and avoid losing annoying messages?

Thank you

**Comment by chrisballinger** [comment]
version 3.2 should be out to beta testers by the end of the month. if you are interested in beta testing, please contact me via email. thanks!
