### ISSUE TITLE
closing the application does not send signal to the server offline

### ISSUE THREAD

**Issue by nespaona** [ChatSecure/ChatSecure-iOS#377]
Hello works well xep-0198, but when the application enters applicationWillTerminate and then restarts all users appear offline.

**Comment by nespaona** [comment]
This began to happen:

self.streamManagement = [[XMPPStreamManagement alloc] initWithStorage: streamManagementStorage];

**Comment by chrisballinger** [comment]
What?

**Comment by nespaona** [comment]
when app is closed (exit(0);).
when I come back in taking the contacts like offline.
this started when it began to streamManagement used

**Comment by nespaona** [comment]
it is just to see if a sign of off the server can be sent, but previously worked with stream line is not rn it becomes to ping
Thank you.

**Comment by chrisballinger** [comment]
Maybe fixed
