### ISSUE TITLE
[iOS 8] Some images/buttons are corrupted

### ISSUE THREAD

**Issue by chrisballinger** [ChatSecure/ChatSecure-iOS#391]
Not sure if this is limited to Zom or not: https://github.com/zom/Zom-iOS/issues/1

**Comment by davidchiles** [comment]
ChatSecure looks fine on 8.4 Simulator. 👻👻👻

**Comment by chrisballinger** [comment]
Can anyone test this on iOS 8 device?

**Comment by chrisballinger** [comment]
Fixed by setting OTRAssets build target to 8.0
