### ISSUE TITLE
ChatSecure-Push SDK integration

### ISSUE THREAD

**Issue by davidchiles** [ChatSecure/ChatSecure-iOS#393]
This is an issue to track progress on push integration

- [x] Create random new account
- [x] Register current device
- [x] Bulk fetch new tokens
- [x] Send token over OTR
- [x] Receive token over OTR
- [x] Send knock message
- [x] Receive knock message and show noticication

**Comment by chrisballinger** [comment]
I'll be working on the server side / certificate stuff today, merging `push` into `develop`, and putting out a new build.
