### ISSUE TITLE
client for ubuntu phone

### ISSUE THREAD

**Issue by jangorecki** [ChatSecure/ChatSecure-iOS#397]
Hi, do you know any fork or maybe there is official support for ubuntu phone?

**Comment by vitalyster** [comment]
you can try https://loqui.im/

**Comment by chrisballinger** [comment]
Sorry, this is the issue tracker for just the iOS client. Twitter would probably be better for general discussion

**Comment by RayMountainer** [comment]
Hi Chris,

I do not think, that twitter is the right place for discussion a project.
i have created a WBS-structured discussion board for enhanced project 
discussion.
If you are interested, I can set you one up for free (it's SAAS).
All you need is a tree-structure of your app/project - the discussion 
board follows that structure than...

a trialboard for having a look /checking functionality is here:
https://c-board.de/trialboard/login/login.php
user: testadmin
pw: admin123

if you are interested and/or need any help with that: just let me know!

-Florian

Am 19.10.2015 um 18:42 schrieb Chris Ballinger:
