### ISSUE TITLE
Cannot create new accounts on self-hosted server, "NSPOSIXErrorDomain" timed out

### ISSUE THREAD

**Issue by moppman** [ChatSecure/ChatSecure-iOS#398]
I run a self-hosted prosody server.
Nameserver is cloudflare, I added a SRV record. Logging into an existing account is fine, but I get the error in the title upon creating a new user account.
Account creation is  explicitely allowed in the config, and works fine e.g. with Pidgin.
Version 3.1.2

EDIT: works fine on Android.

**Comment by stoltenhoff** [comment]
… same problem here (with connection to self-certified arkos-server)

**Comment by chrisballinger** [comment]
Are you attempting to connect via Tor or over a slow connection?

**Comment by moppman** [comment]
No, 10mbit dsl connection. Same for 50mbit LTE network, no Tor.

**Comment by stoltenhoff** [comment]
… i’ve tried it via local server and wlan.

**Comment by chrisballinger** [comment]
Hmmm are you able to run it in the debugger via Xcode to see additional
console output?
