### ISSUE TITLE
Outgoing Message Queue Refactor

### ISSUE THREAD

**Issue by chrisballinger** [ChatSecure/ChatSecure-iOS#401]
We need a better outgoing message queue to better handle poor networks / crypto problems.

The different states for an outgoing message are:
1. Composing (the text entered into chat text field)
2. Encrypting...
3. Encrypted!
4. Sending to server (message grayed out during sending process like Signal?)
5. Sent to server
6. Received by recipient
7. Decrypted by recipient
8. Read by recipient

The error states could be:
1. Error establishing crypto session / crypto error (queue and retry later)
2. Error sending to server (queue and retry later)
3. Error decrypting by recipient (resend after new active crypto session?)
4. Never received delivery receipt after X hours to client that should be sending delivery receipts (resend?)
5. Anything else?

**Comment by davidchiles** [comment]
Message queue merged into omemo. More work needs to be done to catch all the error cases.
