### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by duanhjlt** [ChatSecure/ChatSecure-iOS#421]
./Submodules/CPAProxy/scripts/build-all.sh
No iOS SDK specified. Using the only one available: 9.2
Building architectures: i386 x86_64 armv7 arm64
Building libraries: openssl libevent tor
Building openssl for i386...
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.

**Comment by duanhjlt** [comment]
bash ./Submodules/CPAProxy/scripts/build-all.sh
No iOS SDK specified. Using the only one available: 9.2
Building architectures: i386 x86_64 armv7 arm64
Building libraries: openssl libevent tor
Building openssl for i386...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   317  100   317    0     0     71      0  0:00:04  0:00:04 --:--:--    72
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.

**Comment by duanhjlt** [comment]
Download libevent-2.0.22-stable.tar.gz, and put under "./Submodules/CPAProxy/scripts/build".

**Comment by Shudy** [comment]
AS @duanhjlt said download manually. take a lok to the script build.

you have something like:

OPENSSL_VERSION = "1.0.2e"
LIBEVENT_VERSION = "2.0.22-stable"

In my case, I saw that the openssl version downloaded was 1.02f, so the script never gonna found it. Just change the version in the script. and run it again. Remember to remove folder ../Submodule/CPAProxy/CPAProxyDependencies or never will start the script
