### ISSUE TITLE
Error in fetching `CPAProxy` from pod

### ISSUE THREAD

**Issue by rptwsthi** [ChatSecure/ChatSecure-iOS#425]
I have tried checking out develop branch, and downloading zip. But each time when I ron `pod install it give me following log`

`pod install`
Updating local specs repositories
For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.
Analyzing dependencies
Fetching podspec for `CPAProxy` from `Submodules/CPAProxy/CPAProxy.podspec`
[!] No podspec found for `CPAProxy` in `Submodules/CPAProxy/CPAProxy.podspec`

Is there something wrong with this repo? 

Here are detail from git error message:

>git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree fetch origin 

>git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree pull --log origin develop 
>From https://github.com/ChatSecure/ChatSecure-iOS
> * branch            develop    -> FETCH_HEAD
?Already up-to-date.

>git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree submodule >update --init --recursive 
>Cloning into 'Submodules/CPAProxy'...
>warning: templates not found /usr/local/git/share/git-core/templates
>Permission denied (publickey).
>fatal: Could not read from remote repository.

>Please make sure you have the correct access rights
>and the repository exists.
>Clone of 'git@github.com:ursachec/CPAProxy.git' into submodule path 'Submodules/CPAProxy' failed
>Cloning into 'Submodules/CPAProxy'...
>warning: templates not found /usr/local/git/share/git-core/templates
>Permission denied (publickey).
>fatal: Could not read from remote repository.

>Please make sure you have the correct access rights
>and the repository exists.
>Clone of 'git@github.com:ursachec/CPAProxy.git' into submodule path 'Submodules/CPAProxy' failed
>Cloning into 'Submodules/CPAProxy'...
>warning: templates not found /usr/local/git/share/git-core/templates
>Permission denied (publickey).
>fatal: Could not read from remote repository.

>Please make sure you have the correct access rights
>and the repository exists.
>Clone of 'git@github.com:ursachec/CPAProxy.git' into submodule path 'Submodules/CPAProxy' failed
>Cloning into 'Submodules/CPAProxy'...
>warning: templates not found /usr/local/git/share/git-core/templates
>Permission denied (publickey).
>fatal: Could not read from remote repository.

>Please make sure you have the correct access rights
>and the repository exists.
>Clone of 'git@github.com:ursachec/CPAProxy.git' into submodule path 'Submodules/CPAProxy' failed
>Completed with errors, see aboveCompleted with errors, see above

**Comment by clody** [comment]
You need to generate SSH key and  add the key to Github before you install.
https://help.github.com/articles/generating-ssh-keys/
