### ISSUE TITLE
error: reading data: The file “Secrets.plist” couldn’t be opened because there is no such file.

### ISSUE THREAD

**Issue by krunal7** [ChatSecure/ChatSecure-iOS#426]
When i downloaded this project and tried to open .xcodeproj file it shows me this error...

**Comment by netcanis** [comment]
$ cp OTRResources/Secrets-template.plist OTRResources/Secrets.plist
$ cp ./configurations/OTR_Codesigning.xcconfig.sample ./configurations/OTR_Codesigning.xcconfig

**Comment by chrisballinger** [comment]
You need to make the file yourself, read the README

**Comment by rameshlst01** [comment]
asf
