### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by EmanKassem** [ChatSecure/ChatSecure-iOS#432]
Hello,

I downloaded ChatSecure-iOS-develop.zip and extracted it, when I opened ChatSecure.xcworkspace there were missing files as shown.
![screen shot 2016-01-20 at 4 26 31 pm](https://cloud.githubusercontent.com/assets/16559076/12451580/f4f577dc-bf92-11e5-8089-13d22c428644.png)
I could not ran the demo project.

Any help would be appreciated.

Thanks in Advance.

**Comment by EmanKassem** [comment]
I tried to pod install.

``` ruby
CocoaPods 1.0.0.beta.2 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Fetching podspec for `CPAProxy` from `Submodules/CPAProxy/CPAProxy.podspec`
[!] No podspec found for `CPAProxy` in `Submodules/CPAProxy/CPAProxy.podspec`
```

**Comment by chrisballinger** [comment]
Read the installation instructions in the README
