### ISSUE TITLE
ios 9.2.1 tor account connection problem

### ISSUE THREAD

**Issue by leaf113** [ChatSecure/ChatSecure-iOS#447]
it wont connect to tor accounts. i hit connect and it will load forever. i use VPN Browser - TOR from Art Fusion of the appstore. the account i try to use is already created. 

which app do you use for tor connection, how do i set this up right? do i have to root my phone?

**Comment by chrisballinger** [comment]
Tor is bundled within the app itself. This issue may also have been fixed in 3.1.3. Another possibility is that because SRV lookups are not performed over Tor, you'll need to manually type in the hostname.
