### ISSUE TITLE
CocoaPods update error.

### ISSUE THREAD

**Issue by youhui** [ChatSecure/ChatSecure-iOS#464]
Updating local specs repositories
Analyzing dependencies
Fetching podspec for `CPAProxy` from `Submodules/CPAProxy/CPAProxy.podspec`
[!] No podspec found for `CPAProxy` in `Submodules/CPAProxy/CPAProxy.podspec`

------------------------------------------------------------------------------------------------------------------
 pod 'ChatSecure-Push-iOS', :path => 'Submodules/ChatSecure-Push-iOS/ChatSecure-Push-iOS.podspec'
  pod 'ProxyKit/Client', :path => 'Submodules/ProxyKit/ProxyKit.podspec'
  pod 'OTRKit', :path => 'Submodules/OTRKit/OTRKit.podspec'
  pod 'CPAProxy', :path => 'Submodules/CPAProxy/CPAProxy.podspec'
  pod 'XMPPFramework', :path => 'Submodules/XMPPFramework/XMPPFramework.podspec'
  pod 'IOCipher/GCDWebServer', :path => 'Submodules/IOCipher/IOCipher.podspec'

**Comment by chrisballinger** [comment]
read the README
