### ISSUE TITLE
ChatSecure iOS crash while seraching on large roster

### ISSUE THREAD

**Issue by fenidik** [ChatSecure/ChatSecure-iOS#466]
ChatSecure iOS crash while seraching on large roster ( > 1400 items )
iOS 9.3.1
ChatSecure 3.2

Do you need any additional info?

**Comment by chrisballinger** [comment]
Wow that's quite a lot! Do you have more than one account as well? We have a few reports that suggest others with large contact lists are having the same issue so we're definitely looking into it.

We are analyzing the crash reports from the last 24 hours and are working on fixing the most frequent crashes for a release early next week.

**Comment by chrisballinger** [comment]
We've identified the source of this crash. If you are searching and a contact changes status it will crash because of how the tableview updates are being handled.

**Comment by chrisballinger** [comment]
Fixed in https://github.com/ChatSecure/ChatSecure-iOS/commit/d1bfa60b8e9b0babc58a772f7a62a75ec1aae21e
