### ISSUE TITLE
Cannot join existing MUC

### ISSUE THREAD

**Issue by Kuben123** [ChatSecure/ChatSecure-iOS#480]
I want to join an XMPP pigdin group chat with ChatSecure. How do i do it?

**Comment by chrisballinger** [comment]
You need to be invited by another group member, there's no way to join
within the app itself.

**Comment by rasos** [comment]
Great that we now can use MUCs with https://github.com/ChatSecure/ChatSecure-iOS/issues/129 
Are there any plans to add into the ChatSecure App
1. creation of a MUC
2. set options to a MUC like making it private
3. invite contacts to an existing MUC

**Comment by chrisballinger** [comment]
You can create an MUC by selecting multiple contacts, but you can't set any options, and you can't invite more people to an existing one

**Comment by jankusanagi** [comment]
Looking forward to this, as I have some friends with iOS devices =)

**Comment by mimi89999** [comment]
@Kuben123 Fixed. See #851
