### ISSUE TITLE
Xcode build errors

### ISSUE THREAD

**Issue by celsosz** [ChatSecure/ChatSecure-iOS#491]
Hi everyone. I have some issues in Xcode. There are 9 errors.

------------------------------
Undefined symbols for architecture x86_64:
  "_keccak_digest_init", referenced from:
      _crypto_digest256_new in libor-crypto.a(crypto.o)
      _crypto_digest512_new in libor-crypto.a(crypto.o)
  "_keccak_digest_sum", referenced from:
      _crypto_digest_get_digest in libor-crypto.a(crypto.o)
  "_keccak_digest_update", referenced from:
      _crypto_digest_add_bytes in libor-crypto.a(crypto.o)
  "_keccak_xof_absorb", referenced from:
      _crypto_xof_add_bytes in libor-crypto.a(crypto.o)
  "_keccak_xof_init", referenced from:
      _crypto_xof_new in libor-crypto.a(crypto.o)
  "_keccak_xof_squeeze", referenced from:
      _crypto_xof_squeeze_bytes in libor-crypto.a(crypto.o)
  "_sha3_256", referenced from:
      _crypto_digest256 in libor-crypto.a(crypto.o)
  "_sha3_512", referenced from:
      _crypto_digest512 in libor-crypto.a(crypto.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
------------------------------

The initial Build Instructions (bash, pod, ...) worked fine. But I can't build the project in Xcode.

Can you help me?

Sorry for my english.

**Comment by luisgigar** [comment]
Same problem here.
These were the build errors i mentioned in my #489 comment.

Any solution?

**Comment by celsosz** [comment]
It worked. For Tor version "0.2.8.2-alpha" you must include "libkeccak-tiny.a" library in the project.

I'm not sure but apparently has a flaw in ./configure script Tor version "0.2.7.6". Although the message indicates error in OpenSSL, the error is in "dynamic conftest.c" used during ./configure script. It's not "linkable openssl" error. I think you can fix that too.

**Comment by bktowett** [comment]
> It worked. For Tor version "0.2.8.2-alpha" you must include "libkeccak-tiny.a" library in the project.

How do you include it? Please help

**Comment by x3mall1986** [comment]
> How do you include it? Please help
Add "**libkeccak-tiny.a**" to the folder "**CPAProxyDependencies**" and run **pod install** again to attach lib to project

**Comment by bktowett** [comment]
> Add "libkeccak-tiny.a" to the folder "CPAProxyDependencies" and run pod install again to attach lib to project

@x3mall1986 thanks for the heads up! I'm embarrassed to ask, but where do I find this libkeccak-tiny.a file?

**Comment by vanzan** [comment]
@bktowett I'm having the same problem, did you find the libkeccak-tiny.a file?

**Comment by bktowett** [comment]
@vanzan not yet :-( @x3mall1986 can you please advise or provide a download link?

**Comment by x3mall1986** [comment]
@vanzan compile this script to get lib

https://github.com/mtigas/iOS-OnionBrowser/blob/master/build-tor.sh
