### ISSUE TITLE
Does not compile with CocoaPods 1.0.0

### ISSUE THREAD

**Issue by chrisballinger** [ChatSecure/ChatSecure-iOS#499]
https://github.com/CocoaPods/CocoaPods/issues/5291

**Comment by michaelkirk** [comment]
FYI Signal-iOS is compiling with SQLCipher and CocoaPods 1.0.1 now. 

https://github.com/WhisperSystems/Signal-iOS/blob/master/Podfile.lock#L71

Maybe give it another go?

**Comment by chrisballinger** [comment]
We had some other issues as well with [Mantle](https://github.com/Mantle/Mantle/issues/704), IOCipher-ObjC and our OTRKit library. Could be a good time to look into trying again. :)

Thanks for the heads up!

**Comment by davidchiles** [comment]
I tried with https://github.com/chrisballinger/CocoaPods/commit/3031fc3a22960c4635ce3ad40eb6226cd2cd760a and still have errors.
```
Pods/libsqlfs/sqlfs_internal.h:120:64: Unknown type name 'fuse_fill_dir_t'
Pods/libsqlfs/sqlfs_internal.h:130:64: Unknown type name 'fuse_fill_dir_t'
```

**Comment by chrisballinger** [comment]
That's actually something I fixed in a forked version of the podspec, not sure if I pushed it anywhere. I was able to fix it by changing the order of the source files in the podspec.

**Comment by chrisballinger** [comment]
Fixed
