### ISSUE TITLE
cannot chat

### ISSUE THREAD

**Issue by fvalle1** [ChatSecure/ChatSecure-iOS#505]
I did this:
*create a new account
*show advanced options
*choose OTR.im
*successfully create the account
*try to contact my new account from another xmpp.jp account runnng on adium
*I see the notifier counter, and I see Chat(3) at the top
but I **see no message**!

**Comment by chrisballinger** [comment]
Did you add the OTR.im account as a contact to the xmpp.jp account, or just send a message? You also need to send OTR messages over OTR.im. We do a poor job of showing error messages, so those (3) are probably errors from the server about sending plaintext.

**Comment by fvalle1** [comment]
Filippo

Il 06/06/16 21.28, Chris Ballinger ha scritto:
> Did you add the OTR.im account as a contact to the xmpp.jp account, or
> just send a message? 

add as contact then send the message

You also need to send OTR messages over OTR.im. We
> do a poor job of showing error messages, so those (3) are probably
> errors from the server about sending plaintext.

how may I create a otr connection without first plaintext message?

**Comment by chrisballinger** [comment]
If sending from ChatSecure, click the lock icon and then "initiate". From Adium, click the lock icon and start OTR. If you can't find those, you can also start it by sending the string "?OTR?"
