### ISSUE TITLE
which is the password of my new account?

### ISSUE THREAD

**Issue by fvalle1** [ChatSecure/ChatSecure-iOS#506]
I create an account, I choose automatic password options, but, if I wann log on another device, what do I have to do? I don't know which is my password!

**Comment by masvil** [comment]
Good question.

**Comment by fvalle1** [comment]
I'm not joking!

Chatsecure creates one, but I have no idea of how to copy or change it!

Filippo

Il 05/06/16 18.22, masvil ha scritto:

**Comment by chrisballinger** [comment]
This is a known issue and will be addressed in a future release
