### ISSUE TITLE
Stay logged out when I manually logout

### ISSUE THREAD

**Issue by n8fr8** [ChatSecure/ChatSecure-iOS#510]
The app automatically logs in all accounts when it restarts, and maybe some other times, even if I have manually logged out of an account. Sometimes I really really don't want an account to login.

**Comment by chrisballinger** [comment]
You need to disable the auto-login feature for that account, which is a setting that appears during the login view / account details screen. You have to log out first if you're already logged in to see it, and log in again to save the setting. I think we'll change that to save when you dismiss the view (without logging in) as well.

**Comment by n8fr8** [comment]
Ah okay. Right, thanks!
