### ISSUE TITLE
Allow any XMPP server

### ISSUE THREAD

**Issue by samrocketman** [ChatSecure/ChatSecure-iOS#525]
I run my own personal XMPP server.  It would be great if there were advanced configuration options where I could configure my own server.  The App is nice but I care about privacy enough that I control the full stack of my chatting activities with friends.

I looked in the advanced settings and couldn't find where I could configure this.

I found a related issue #118 but I wanted to open a separate feature request with less inflamatory conversation.

Also, Subject Altermative Name (SAN) certificates support validating by IP so a DNS name is not required for TLS negotiation.  Please tell me your thoughts and thanks for making this open source.

Some details about my configuration.

* My XMPP server is openfire (regularly updated to latest stable)
* My Server OS is currently CentOS 7 headless with selinux enabled, firewall configured, logs centralized elsewhere following normal practices for sysadmin stuff.
* My ChatSecure 3.2.2 client is an iPhone 5s running iOS 9.3.2
* I manage my own certificate authority to sign and validate server or client certificates.  I issue myself SAN certificates.

**Comment by chrisballinger** [comment]
We support both creating accounts on custom servers (requires SRV) or manually adding existing accounts (doesn't require SRV). We also support cert pinning, which allows you to pin your custom certs even if they don't validate against the default cert store.

In settings go to New Account -> Add Existing Account -> XMPP -> and then fill in your account details. If the JID domain doesn't match the server domain and doesn't have a SRV record you can enter the server domain manually in the hostname field.

For Create New Account, you go to Advanced, click on the Server cell, and then enter your server domain in the Custom field.

Let me know if you have any further issues.

**Comment by samrocketman** [comment]
Ah! I missed that; thank you.
