### ISSUE TITLE
Beta 3.2.3 (35): Returns NSPOSIXErrorDomain; Code: 65; No route to host - IPv6 related?

### ISSUE THREAD

**Issue by TaroPuff** [ChatSecure/ChatSecure-iOS#530]
First apologies for etiquette. No idea if appropriate to report beta errors here.

Beta 3.2.3 (35): Connecting to certain hosts (my own, chinwag.im, jabber.at) results in:

```
Domain: NSPOSIXErrorDomain
Code: 65
UserInfo: {
  NSLocalizedDescription = "No route to host";
  NSLocalizedFailureReason = "Error in connect() function";
}

```
Connects fine with dukgo.com and xmpp.jp.

My quick check shows duckgo.com and xmpp.jp doesn't have IPv6 AAAA in DNS, the other 3 do. My testing has been a short one on a hunch it's IPv6-related. Apologies if I am mistaken.

**Comment by chrisballinger** [comment]
Definitely the right place! We did make some changes that would affect that, but I wouldn't think that it would cause failure.

The internal socket library used to only connect to IPv4 records, and we recently changed it to prefer IPv6 if available, but it won't fall back to IPv4 if the v6 connection fails. There is some code to try both protocols and choose the winner but it hasn't been merged yet.

Can your client connect to IPv6 hosts in general? Are the records set up properly and work on a v6-only client?  What's the result of this test? http://test-ipv6.com

**Comment by TaroPuff** [comment]
I didn't even have to visit test-ipv6.com to know, but did anyway just to be sure, and it's a poor 0/10. My Asian ISP does not provide IPv6 at all.

Did see that change in XMPPFramework (I'm assuming that's where the IPv6 connection happens). Will watch for any beta updates and report success or failure.

Thanks!

**Comment by chrisballinger** [comment]
So I'm betting that the DNS lookup is returning IPv4 and IPv6 and the system tries to connect to IPv6 first and fails. I'll see if I can fix this in the next beta.

**Comment by TaroPuff** [comment]
I can report this issue seems fixed in 3.2.3 (36).

**Comment by chrisballinger** [comment]
Awesome! I was about to ask :)

**Comment by ashishgupta301** [comment]
I have same problem.

How can I fixed it?
