### ISSUE TITLE
App crashing on luanch; Still crashes on reinstall

### ISSUE THREAD

**Issue by johnhearfield** [ChatSecure/ChatSecure-iOS#531]
Phone specs: iPhone 6s 128GB UK
iOS 9.3.1

Only found out about this today. Not sure what the problem could be and not sure how to get crash logs on iOS

**Comment by johnhearfield** [comment]
Had to restart the phone to get it to work surprisingly.

**Comment by chrisballinger** [comment]
Very weird! Is this on the app store release or the beta? Seems like an Apple bug if it was fixed on restart.

It should prompt you to send a crash report via HockeyApp on the next successful launch (or it will automatically send if you've enabled that feature in the past)

**Comment by johnhearfield** [comment]
This is with the current App Store version. I didnt see any HockeyApp dialogs about a crash report.

**Comment by chrisballinger** [comment]
Let me know if it happens again, hopefully it was an isolated incident.
