### ISSUE TITLE
ChatSecure not available for the French market??

### ISSUE THREAD

**Issue by thundergreen** [ChatSecure/ChatSecure-iOS#544]
Hey guys. For a loooong time i try to obtain Chatsecure here in France, but it's not available for me in French Market. Can you please push it there also?

**Comment by vitalyster** [comment]
duplicate of #127

**Comment by thundergreen** [comment]
thanks.. CLOSED and not solved :(

**Comment by thundergreen** [comment]
Would be nlice of chat secure could be released .cause registration in USA
is a pain in the ass

Thorsten Fröhlich

Am 08.08.2016 12:38 schrieb "vitalyster" <notifications@github.com>:
