### ISSUE TITLE
Implementing Android on Android Studio

### ISSUE THREAD

**Issue by johnnyAnd** [ChatSecure/ChatSecure-iOS#556]
Is there any tutorial for implementing Chat Secure on Android Studio ?

In code I dont see code for android either.

Thanks

**Comment by ablyeom** [comment]
This is issue tracking for iOS Client.

Maybe you should find in [here](https://dev.guardianproject.info/projects/gibberbot).

**Comment by n8fr8** [comment]
Zom is a new project based on ChatSecure Android that is fully updated for Android Studio. You can find it here: https://github.com/zom/Zom-Android
