### ISSUE TITLE
recalitrant family

### ISSUE THREAD

**Issue by freezePuppies** [ChatSecure/ChatSecure-iOS#569]
I have convinced family with android devices to license- and employ Conversations.  OTR was too much of a hurdle for some, the very same subset apparently capable of tuning facebook privacy settings, consequently uninstalling the app.  Since the advent of omemo I was able to convince them to try Conversations again -- a lasting Jabber Texting conversion.

I face the same hurdle with ChatSecure on iOS devices.  Other than trying to switch them to root'd android devices what would you people suggest?

**Comment by chrisballinger** [comment]
We are getting closer to OMEMO support by the day.
