### ISSUE TITLE
No automatic login after iOS Push notification

### ISSUE THREAD

**Issue by ecky-l** [ChatSecure/ChatSecure-iOS#577]
My SSL certificate issue has been resolved ( [issue #575 ](https://github.com/ChatSecure/ChatSecure-iOS/issues/575) ), but now there is another:

When ChatSecure is in the background on my iPhone for some time, I get logged out of my account. Then, when I chat to this account from another test account, I get a push notification on the iPhone. Then I unlock the iPhone, open ChatSecure and want to reply - but I am not logged in anymore. I need to open the settings from the upper right corner and tap on my account to get logged in again. Then I evtl. get some messages about failed OTR encryptions. Especially the other side gets also some of those messages of failed OTR encryption. This might be a separate issue, but is somehow related.

The main issue here is, that I should get logged in automatically when I open ChatSecure, after I get a push notification. With no push notification this is mostly the case (sometimes not), but after a push notification it is always not working.

**Comment by chrisballinger** [comment]
This is a known bug that I believe is fixed in the latest development branch. Our OMEMO support is priority #1 and solves the OTR issues. Would you be interested in joining our beta test group?

**Comment by goldzilla** [comment]
are you looking for more beta-testers?

**Comment by Zjemm** [comment]
Count me in, would like to beta test to

**Comment by chrisballinger** [comment]
@ecky-l @goldzilla @Zjemm Join the beta here: https://goo.gl/forms/0Tgoba0mXkGCGGDN2

**Comment by thundergreen** [comment]
Jiahaaa..Sounds awesome

Thorsten Fröhlich

Am 18.11.2016 01:15 schrieb "Chris Ballinger" <notifications@github.com>:

**Comment by chrisballinger** [comment]
I think this is fixed
