### ISSUE TITLE
First message after short break lost

### ISSUE THREAD

**Issue by fichtennadel** [ChatSecure/ChatSecure-iOS#586]
**Problem: First message after a short break is lost**

**Versions:**
Client A: ChatSecure 3.2.3 on iOS 10.1
Client B: Miranda 0.10.17.0 on Win7
Server: yax.im
OTR: Off

**Steps to reproduce issue:**
1. A + B exchange some messages while both being online
2. A idles/locks phone
3. both send no messages for ~5 minutes
4. _B sends a new message, which is never received at A._ 
5. B sends a second message, which is received.

**Chat log in A/ChatSecure:**
    Today 13:15
1
2
3
5

**Chat log in B/Miranda:**
  13:15:32: 1
  13:15:33: 2
  13:15:34: 3
  13:15:45: A signed off (was Online)
  13:15:46: A signed on (Online)
  13:20:13: 4
  13:20:16: A signed off (was Online)
  13:20:16: A signed on (Online)
  13:20:20: 5
  13:21:25: A signed off (was Online)
  13:21:26: A signed on (Online)

Reproducable at will. 

Other iOS client "JabberB" does not miss message "4", so I guess it's related to ChatSecure and not (primarily) a problem at yax.im or Miranda.

**Comment by chrisballinger** [comment]
Is this related to stale OTR sessions?

**Comment by fichtennadel** [comment]
Please define "stale OTR sessions".

I've toyed around with OTR the day before using Miranda NG's OTR plugin, but had troubles with carbon copies sent to yax.im Android app, which broke OTR and totally confused Miranda NG (which actually started sending messages to self after first cc'ed message [xep-0280 seems to be broken in Miranda NG]). I turned off OTR in ChatSecure, manually removed the fingerprint of "B" in ChatSecure's settings and also had to remove the OTR plugin in Miranda NG to make messages work again at all. Then I tried to sort out the cc issues but finally gave up.

But that was about 12 - 14 hours before and on a different machine, when I then tried Miranda (no "NG"). I've never enabled OTR for any of the chats I tried between ChatSecure and Miranda on this machine, for which I've opened this issue.

Is there any way to purge these "stale OTR sessions" on demand and retest?

**Comment by fichtennadel** [comment]
Tried again more than 24 hours later, even removed and reinstalled ChatSecure from client A. Still the same: messages lost, no push.

**Comment by chrisballinger** [comment]
I'm still not sure what's going on here, but we'll keep an eye on it. We will be putting out a beta soon which might improve things for you.

**Comment by chrisballinger** [comment]
@fichtennadel Join the beta here: https://goo.gl/forms/0Tgoba0mXkGCGGDN2

**Comment by fichtennadel** [comment]
Tried again with beta 4.0, issue seems to be gone, no more lost messages when using two accounts on same server.

There is some glitch when using accounts on differents servers (tried with dukgo.com and yax.im):
if account on one (dukgo.com) idles for some time (phone locked for more than ~12minutes), it appears as offline to other (so far so good), but it cannot be reached anymore, error message "service unavailable" in 2nd client (yax.im on Android). 
But this could also be related to something on server side, so I didn't investigate further. 

My use case is two accounts on one server, to this issue is solved for me in beta 4.0

**Comment by chrisballinger** [comment]
@fichtennadel If servers don't support offline message queueing you'll see that "service unavailable" message. Nothing you can do about that unless you manually send a Knock to wake them up before sending messages.
