### ISSUE TITLE
Omemo unable to encrypt to buddy

### ISSUE THREAD

**Issue by davidchiles** [ChatSecure/ChatSecure-iOS#587]
Steps to reproduce:
1. Normal conversation using OMEMO two device and different accounts
2. delete one account and re add it while the other device is logged in (not sure if it's important it remains connnected)
3. The re-added account won't be able to send messages to the other device because it won't be able to encrypt to that buddy. It's unable to fetch the device bundle for that buddy.

There might be something wrong with the device list and how bundles are fetched.

**Comment by chrisballinger** [comment]
The SignalStore might have remnants of that account that no longer match up with our records?
