### ISSUE TITLE
Does not Work on iPad Pro LTE 2016 

### ISSUE THREAD

**Issue by zem** [ChatSecure/ChatSecure-iOS#601]
Hi, 

In short: Unfortunately it simply does not work! 

The whole App feels a bit slow, and I did not manage to bring any message out. 
I can add my account and do the login. I can select one of my friends and open a Chat. 

It is hard to use the "start encrypted chat" button, I have to touch the functions there long to get a response. 

When I type a message the send button becomes blue, but I am unable to press it, no matter how hard I try. 

I did Try to reinstall the App but no difference (means I get the same setting again)  do you have any Ideas? 

regards 
     Hans

**Comment by chrisballinger** [comment]
The App Store version has issues on iPad at the moment. We will be
releasing a new version "soon" that fixes these issues.

**Comment by chrisballinger** [comment]
@zem Join the beta here: https://goo.gl/forms/0Tgoba0mXkGCGGDN2
