### ISSUE TITLE
Message sorting (4.0 [48])

### ISSUE THREAD

**Issue by ronnicek** [ChatSecure/ChatSecure-iOS#606]
I have a bit problem with message sorting. When message has been delivered from push it stays down and my NEW messages are upward this message.

[![2016-11-22 22-52-21-1.jpg](https://s13.postimg.org/te8tswkh3/2016_11_22_22_52_21_1.jpg)](https://postimg.org/image/e5iwf4qsj/)

Messages 2, 3 and 4 has been send after message 1. I think when I read that message from push, it should normally continue with my messages which I send.

So:
Push message
message 1
message 2
message 3

Maybe we need implementation of XEP-0280: Message Carbons?

**Comment by ronnicek** [comment]
And here is one more screenshot for understanding :) [all blue messages (mine) were sent after I open chat with all push messages]

[![2016-11-24 08-45-18-1.jpg](https://s17.postimg.org/819mfn1pb/2016_11_24_08_45_18_1.jpg)](https://postimg.org/image/caecht4yj/)

**Comment by ronnicek** [comment]
This looks ok now in latest beta release! Thanks for solving 👍  I will do more test during weekend.

**Comment by chrisballinger** [comment]
Interesting.. I don't think we changed anything :)

**Comment by ronnicek** [comment]
Then it's without work 👍 closing.. working well now :)
