### ISSUE TITLE
OMEMO doesn't work with Dukgo and possibly other servers

### ISSUE THREAD

**Issue by chrisballinger** [ChatSecure/ChatSecure-iOS#607]
This may be due to a broken PEP implementation because they run an old version of Prosody. Conversations has code to detect broken PEP implementations, but there's not really a reliable way to test if it's broken. I reached out to Dukgo to see if they could update their server, which might improve the issue.

If this remains a problem we may want to reconsider the default server options.

**Comment by asiamov** [comment]
This is also the case for jabber.de. 
Own OMEMO fingerprint is visible on both sides but the conversation can only be encrypted with OTR.

**Comment by chrisballinger** [comment]
@asiamov This is fixed in beta 49
