### ISSUE TITLE
Timestamps appear to be missing

### ISSUE THREAD

**Issue by joostrijneveld** [ChatSecure/ChatSecure-iOS#610]
It could be that I'm grossly overlooking them, but I don't see timestamps anywhere for messages received in the past. The UI could be like Whatsapp, with small subscripts, or like iMessage, with timestamps sliding in when dragging from the right (or even with inline timestamps after longer idle intervals).

**Comment by chrisballinger** [comment]
They are supposed to appear every N messages after a certain time interval, but we never had a way to view the exact timestamp of a message.

**Comment by joostrijneveld** [comment]
Hmm, I see those now. It seems I overlooked them earlier, as the conversation I used to test consistent of fairly frequent messages without much idle time in between :)

Feel free to close this issue if you feel like this is not something that needs extension/improvement anytime soon.
