### ISSUE TITLE
OMEMO unavailable

### ISSUE THREAD

**Issue by cryptix** [ChatSecure/ChatSecure-iOS#615]
Hey,

I'm having issue using OMEMO when messaging a friend using Conversations. I have been messaging my with him using gajim's OMEMO plugin on my end, which worked fine.

![](http://i.imgur.com/RiLUqfa.jpg)

I see my new device key in Gajim but I don't get his or my messages in chatSecure when I write from gajim. Except these "not supported" messages when I log in again with ChatSecure after we exchanged a couple of messages.

![](http://i.imgur.com/aaYacRu.jpg)

If I try to write from ChatSecure, it tries to establish an OTR session with my friend.

i will also make a 2nd ID soon to test against gajim myself.

**Comment by chrisballinger** [comment]
Woah that's very weird. What server configuration are you using? We don't have MAM support yet so it's strange to see your own messages synced back to our client.

**Comment by chrisballinger** [comment]
We tried to reproduce with Gajim OMEMO but couldn't figure it out at the moment. We don't support OMEMO and Carbons either, and haven't tested syncing your own message history. The "clock" icon on the messages means we aren't handling the carbons properly.

**Comment by ronnicek** [comment]
I am not able to do that also.. but it's funny, that from Gajim -> ChatSecure I get OMEMO (according to ChatSecure), but from ChatSecure -> Gajim it wants always OTR. And I am not able to choose OMEMO in contact settings in ChatSecure also.

[![2016-12-02 10-59-48 2570.png](https://s16.postimg.org/i6u8uk085/2016_12_02_10_59_48_2570.png)](https://postimg.org/image/s459nm7tt/)

**Comment by ronnicek** [comment]
I had intersting situation now..

I wrote from my Gajim to ChatSecure. All messages were OMEMO as in previous screenshot which I provide here. Then I was able to respond with OMEMO first two messages. Then I went to (i) to change Best available to OMEMO only (it was active - woohoo!). And after that, o memo stop working and I have OMEMO unavailable again :-/. In contact option, OMEMO was Verified by TOFU.

In Gajim I got again lot of **Unencrypted** + ?OTR message, then ChatSecure sent me first OMEMO message. After that, ChatSecure disconnect and connect again (no idea why, but I found out it's doing quite frequently). After that, I got second OMEMO message after that OMEMO is unavailable.

**Comment by chrisballinger** [comment]
Wow thanks for the detailed feedback. I'll have to think about how this would be possible.

Normally if you receive an initial OMEMO message in ChatSecure you'll automatically be able to respond because a session is established by receiving the message. It shouldn't ever stop working and have OMEMO go away unless the device is untrusted. What I think is happening, is that the Gajim client isn't working properly and the devicelist for the Gajim user is empty.

The OTR messages are intentional but should be filtered by Gajim. We need to do both OTR and OMEMO at the same time so the OTRDATA and Knock functionality continues to work.

**Comment by chrisballinger** [comment]
@cryptix @ronnicek Have you guys tested the latest beta? It allows you to select OMEMO only which will prevent the OTR garbage.

> And in ChatSecure I still have "Send OMEMO encrypted message", but in contact option (i) I am don't have any OMEMO fingerprint to verify. I had unavailable OMEMO checked, when I change it to Best Available it changes to OTR.

It will allow you to send an OMEMO message if the server says there are devices, but it wont fetch the device bundle(s) until you actually send the message, so you can't verify fingerprints for the first message. This is somewhat intentional because we're doing TOFU.

**Comment by ronnicek** [comment]
Hmm.. It's still there I think..

When I send message from Gajim -> ChatSecure as OMEMO in Gajim it looks like this:

‎

> [20:07:09] ‎OMEMO encryption disabled
> ‎[20:07:10] ‎OMEMO encryption enabled 
> ‎[20:07:10] ‎You received a new Fingerprint. Until you make a trust decision you can only receive encrypted Messages from that Device.
> ‎[20:07:18] ‎3gajim‎: Hello
> ‎[20:07:22] ‎Received plaintext message! Your next message will still be encrypted!
> ‎[20:07:22] ‎2chatsecure‎: **Unencrypted** ?OTRv23?
> <b>2chatsecure@vypni.net</b> has requested an <a href="https://otr.cypherpunks.ca/">Off-the-Record private conversation</a>.  However, you do not have a plugin to support that.
> See <a href="https://otr.cypherpunks.ca/">https://otr.cypherpunks.ca/</a> for more information.

(i didnt restart Gajim, so I dont have OTR keys on that account, when I have it send ?OTR messages)

And one more scenario:
- Set on my Gajim buddy "Best available" encryption"
- Set ChatSecure to Chats view without any chat opened
- Go on/offline on Gajim
- Recieved ?OTR messages from ChatSecure (without any opened window with that account on any of client)

‎> [20:13:19] ‎OMEMO encryption enabled 
> ‎[20:12:52] ‎2chatsecure‎: **Unencrypted** ?OTRv23?
> <b>2chatsecure@vypni.net</b> has requested an <a href="https://otr.cypherpunks.ca/">Off-the-Record private conversation</a>.  However, you do not have a plugin to support that.
> See <a href="https://otr.cypherpunks.ca/">https://otr.cypherpunks.ca/</a> for more information.

**Comment by ronnicek** [comment]
- Start ChatSecure
- Open chat with user
- There is "Send OMEMO encrypted message"
- I type some message and send, there is "big yellow !"
- I go to profile and check Show Andvanced Encryption Settings then OMEMO and OMEMO & OTR is gray out
- I can send OMEMO message from Gajim client to ChatSecure. ChatSecure it shows normally as OMEMO message, but I am not able to respond back..

@chrisballinger is this working for you or you have same bug? Because I think OMEMO is unusable with these bugs.. :-/

**Comment by chrisballinger** [comment]
Are there existing keys for that contact? Can you show a redacted screenshot of the Profile screen?

I've seen sporadic issues where the server returns an empty device list (or we interpret the response as one), which we interpret as "permanently removed" and will untrust the device without a way to re trust. If there is an existing greyed out / untrusted key with a "last seen" date that's pretty recent, this might be what you're seeing.

If you don't have visible (greyed out) keys for that contact, can you also mention the history of the two accounts? How was each account created and with what client and server, etc? Are these accounts used simultaneously on other devices? Was an OMEMO session successfully established in the past?

**Comment by ronnicek** [comment]
Hi,

When I want to check it now, I was not able, but profile for contact in Gajim was always "empty" for OTR/OMEMO keys.

When I send message from ChatSecure to Gajim contact, he recieve something like this (but in ChatSecure it shows as OMEMO encrypted):
> [10:08:04] ‎gajimContact‎: The following message received from gajimContact@domain.net/mobile was *not encrypted*: [Test]

Now I have OTR key and OMEMO key (which is different then I have in Gajim :-/). See screenshot below:
In ChatSecure, there is OMEMO key: b2ed...
In Gajim my own fingerprint is: 4641...

![2016-12-20 10-10-45 2671](https://cloud.githubusercontent.com/assets/3885042/21344717/6c629e8c-c69d-11e6-828f-169826f8185d.png)

![screenshot from 2016-12-20 10-20-14](https://cloud.githubusercontent.com/assets/3885042/21344858/3005f2d0-c69e-11e6-8c3b-02b8fe4d55a5.png)

**Comment by chrisballinger** [comment]
We made some changes in the latest beta (58) that should fix this. If it doesn't fix itself automatically, manually opening the (i) profile page will refresh the devicelist.
