### ISSUE TITLE
Couldn't pull down sub modules.

### ISSUE THREAD

**Issue by gstream** [ChatSecure/ChatSecure-iOS#616]
Hello

I was trying to clone repo as described but get failed.

This is what I am getting when I've tried to pull down repo.
Submodule 'Submodules/xmpp-server-list' (git@github.com:ChatSecure/xmpp-server-list.git) registered for path 'Submodules/xmpp-server-list'
Cloning into 'Submodules/CPAProxy'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:ursachec/CPAProxy.git' into submodule path 'Submodules/CPAProxy' failed

Any help would appreciated.
Thanks

**Comment by chrisballinger** [comment]
Add your SSH key to Github
