### ISSUE TITLE
error: cannot run C compiled programs

### ISSUE THREAD

**Issue by muneikh** [ChatSecure/ChatSecure-iOS#622]
I have been trying to run ChatSecure but always get stuck during the following step:
bash ./Submodules/CPAProxy/scripts/build-all.sh

> checking whether we are cross compiling... configure: error: in `/ChatSecure-iOS/Submodules/CPAProxy/scripts/build/libevent-2.0.22-stable':
> configure: error: cannot run C compiled programs.
> If you meant to cross compile, use `--host'.
> See `config.log' for more details

Attached is the config.log file.
[config.txt](https://github.com/ChatSecure/ChatSecure-iOS/files/639766/config.txt)

Has someone else also encountered the similar issues? Please let me know if there is any configuration change I need to make.

**Comment by chrisballinger** [comment]
Do you have Xcode 8.1 installed?

**Comment by muneikh** [comment]
Yes, I have Xcode 8.1 installed.

**Comment by hamzaozturk** [comment]
cd ./Submodules/CPAProxy/
git checkout master

then it will work
