### ISSUE TITLE
iOS beta 55 auto-joins MUCs when invited

### ISSUE THREAD

**Issue by ge0rg** [ChatSecure/ChatSecure-iOS#626]
Sending a mediated MUC invite to ChatSecure 4.0 makes it auto-join the
MUC with the bare JID as the nickname.

So initially you know the JID of the user, and afterwards you can know
the full JID (including the resource) and the JID is exposed to all
MUC participants, irregardless of the MUC privacy settings.

I think this is something where the nickname should be used instead.

Also it is probably a bad idea to auto-join any MUCs, it's better to limit that behavior to invitations from people you trust already.

It is also a bad idea to join "classic" MUCs, i.e. IRC-style chat rooms.

I've written a bit more about it in a related issue, https://github.com/siacs/Conversations/issues/358#issuecomment-267059798

Swift for example is using an additional tag on inivtations to limit the behavior, though it is not bullet-proof either: https://github.com/swift/swift/blob/master/Swiften/Parser/PayloadParsers/MUCInvitationPayloadParser.cpp#L20

I'd love to see a common approach to this problem, shared by all modern mobile XMPP clients.

**Comment by chrisballinger** [comment]
Fixed in 161c857

**Comment by ge0rg** [comment]
We are trying to set up a common understanding of ad-hoc MUCs in the xmpp wiki: [Easy Group Chats](https://wiki.xmpp.org/web/Easy_Group_Chats). It would be great if you could document your behavior and/or adopt the consensus, as soon as it's created.
