### ISSUE TITLE
MUC UI is totally broken

### ISSUE THREAD

**Issue by ge0rg** [ChatSecure/ChatSecure-iOS#627]
This is probably not something you are going to address soon, but due to #626 today I landed in a MUC by accident, and it turned out that the UI is totally broken:

* instead of the MUC JID or name (from `disco#info`), the subject is shown in a very small print at the top
* message senders are not properly identified, sometimes you see a JID but mostly all you see is a grey circle.

Screenshot:

![img_0043](https://cloud.githubusercontent.com/assets/165635/21192748/e55df17e-c229-11e6-8361-a8e7083bef44.PNG)

**Comment by ge0rg** [comment]
Updated to beta 56. I'm still in the MUC (forgot to leave it yesterday).

Now I got a bunch of ChatSecure notifications, containing the MUC's subject instead of nickname/body:

![img_0045](https://cloud.githubusercontent.com/assets/165635/21256832/ece95df6-c374-11e6-96e2-e91c9e540e7f.PNG)

And when I clicked on it, I landed in this screen without any decor or any way to leave:

![img_0044](https://cloud.githubusercontent.com/assets/165635/21256776/8f9c8a92-c374-11e6-9a87-acaf3997856e.PNG)

Killing ChatSecure and opening the MUC from the "Chats" window worked normally, though. And it was not possible to reproduce the issue again.

**Comment by ge0rg** [comment]
P.P.S: Deleting the MUC caused the app to crash. I've submitted a report.

**Comment by chrisballinger** [comment]
Ohhhh brother. :(

**Comment by ge0rg** [comment]
Another problem (only noticed it in beta 58, not sure if it existed before):

Private messages from a MUC participant appear in the Chats list as "mucjid@chat.yax.im" not as the name of the participant.

**Comment by chrisballinger** [comment]
Ha, I'm surprised that even worked at all because we never handled that scenario.

**Comment by ge0rg** [comment]
Another small nitpick: when the subject/topic of the room is changed while you have the "Group Chat" tab open, the change is not reflected - you need to close the chat and reopen it from the conversations list to  see the new topic (it's also correctly displayed in the conversations list).

**Comment by ge0rg** [comment]
Another (major) nitpick: when opening a MUC from the "X new messages" notification, it's lacking the title bar:

![img_0049](https://cloud.githubusercontent.com/assets/165635/23802008/3eb922fe-05b2-11e7-84d3-20b96d663c08.PNG)

**Comment by mimi89999** [comment]
@ge0rg MUC got improved in 4.2.0. There are still some problems, but we have peperate issues for them now.

@chrisballinger I think this issue can also be closed.

**Comment by chrisballinger** [comment]
Yeah, now it's only mostly broken. :)
