### ISSUE TITLE
Any non-optional component with a hard dependency on XCode >7? (Build for iOS 7)

### ISSUE THREAD

**Issue by andreygursky** [ChatSecure/ChatSecure-iOS#632]
Hi,

I haven't found a prebuilt ChatSecure for iOS 7.1. It mens I'd have to build it by myself. It seems the easiest and safest way is to use XCode 7, since the support of iOS <8 has been dropped officially since XCode 8 (though it might be still possible to enter the target 7.1 manually). Does ChatSecure itself or any of its non-optional 3rd-party libs have a hard dependency on XCode 8? If yes, a workaround suggestion would be very welcome.

Thanks.

**Comment by chrisballinger** [comment]
ChatSecure depends heavily on Swift and dynamic frameworks which aren't available until iOS 8, as well as many of the new iOS 8+ APIs. Sorry! Any device manufactured after late 2011 should support iOS 8 or higher.

**Comment by andreygursky** [comment]
Too bad for one of my communication partners (and thus me also). Thanks for clarification. BTW, github shows that "only" 9.7% of ChatSecure is written in Swift.

**Comment by chrisballinger** [comment]
It's pretty deeply embedded though. You'd be better off just updating to a newer device. You can find used iOS devices for pretty cheap.

ALSO if you're looking for security, iOS 7 (and I think iOS 8) are no longer receiving security updates from Apple, so that's another reason to upgrade.

**Comment by andreygursky** [comment]
> ALSO

Indeed, I should also take this into account and check. Thanks for the reminder.
