### ISSUE TITLE
CPAProxyDependencies

### ISSUE THREAD

**Issue by azizcode** [ChatSecure/ChatSecure-iOS#638]
I just git file and have no this list file on CPAProxyDependencies Folder but i have no file in this folder

![b683a20c-b4ee-11e5-97d9-9c12471be90f](https://cloud.githubusercontent.com/assets/5786359/21607157/d8c955b2-d1e6-11e6-861b-6b71c53c20bb.png)

Where is i can this file manually?

**Comment by chrisballinger** [comment]
I have no idea what you're trying to say
