### ISSUE TITLE
Show "expired" label on OMEMO fingerprints

### ISSUE THREAD

**Issue by chrisballinger** [ChatSecure/ChatSecure-iOS#643]
If you trust a fingerprint but it gets too old, we untrusted it, but still display the old trust state.

**Comment by Fab2100** [comment]
It is possible to disable this behavior in the future? Maybe as an option?
If I wrote to a friend and he uses a tablet and a phone I have to re-enable the OMEMO fingerprint every couple days for the device he was not using with me in our conversation.

**Comment by chrisballinger** [comment]
It's expiring every couple days? I believe it should last 30 days by default if you haven't received a message from them. There is a reasoning behind auto-expiring keys that remain unused for long periods of time, but perhaps that timeout default could be increased somewhat significantly.

**Comment by Fab2100** [comment]
Yes, for me it's exspiring every 5 to 7 days or something like that. 
It would be great to have an option to change this behavior.

**Comment by chrisballinger** [comment]
Will revisit if this is a problem
