### ISSUE TITLE
Treat >=32 bytes OMEMO 'keys' as containing the auth tag.

### ISSUE THREAD

**Issue by iNPUTmice** [ChatSecure/ChatSecure-iOS#647]
in 'siacs' OMEMO the auth tag is concatenated to the payload. In preparation to being compatible with the actual XEP ChatSecure should check if the key - after it has been processed (decrypted) by libsignal - is longer or equal to 32 bytes. If that's the case it should treat those bytes as having the key as well as the auth tag. The first 16 bytes are always the key and the rest (usually 16 bytes as well) are the auth tag. 

This way we can make all OMEMO libraries be compatible with that new mode from a receiving perspective  and afterwards switch over our clients to make the change on the sending side as well.

Conversations beginning with https://github.com/siacs/Conversations/commit/f0c3b31a42ac6269a0ca299f2fa470586f6120be has support for parsing the auth tag from the 'key' and also (disabled) support for generating this.

**Comment by chrisballinger** [comment]
Fixed in https://github.com/ChatSecure/XMPPFramework/commit/5c9f1973e52690cfe8c9386d63a1e5d3ad452466

**Comment by chrisballinger** [comment]
Fixed in 4ce77ced

**Comment by vanitasvitae** [comment]
@chrisballinger Could you start sending in the new key format? Smack no longer supports the legacy format and I keep getting bug reports about Chatsecure sending the old format. I think enough time should have passed for everyone to upgrade their clients :)

**Comment by chrisballinger** [comment]
Really? I thought I already flipped the switch in the newer releases. Will take a look.

**Comment by iNPUTmice** [comment]
Can we get an update on whether or not ChatSecure has started sending auth tags as part of the key? Conversations and Gajim will soon stop accepting auth tags that are not part of the key.

**Comment by chrisballinger** [comment]
@iNPUTmice I'll have to take another look, it's been a while
