### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by chrisballinger** [ChatSecure/ChatSecure-iOS#649]
Sigh

**Comment by chrisballinger** [comment]
Xcode 8.3 requires Swift 3 and will probably be released in 1-2 months.

**Comment by davidchiles** [comment]
Dependencies:
- [ ] [ChatSecure-Push](https://github.com/ChatSecure/ChatSecure-Push-iOS)
- [ ] [YapTaskQueue](https://github.com/davidchiles/YapTaskQueue)
- [ ] ParkedTextField
