### ISSUE TITLE
Accounts get stuck on "Pending Approval"

### ISSUE THREAD

**Issue by radiosilence** [ChatSecure/ChatSecure-iOS#651]
Steps to replicate:

1. Set up two accounts on the same server/whatever.
2. Add one account as buddy from the other account.
3. Hi the green tick to approve.
4. Now both say Pending Approval.

Tested with dismail.de, DDG, talker.to and null.pm

If you do it with a different physical device, only the requester gets stuck on Pending Approval.

**Comment by chrisballinger** [comment]
Thanks for the feedback! I've seen this intermittently as well.
