### ISSUE TITLE
Add prekey='true' attribute to key element

### ISSUE THREAD

**Issue by iNPUTmice** [ChatSecure/ChatSecure-iOS#653]
When the key element contains a PreKeySignalMessage it should contain an attribute called prekey with the value of true. This is also described in the current XEP.

Non prekey SignalMessages don't need to contain the attribute (not set to false).
Together with #647 this is a rather small change that opens up the path for some changes in the future.

**Comment by chrisballinger** [comment]
Thanks for the reminder :)

**Comment by chrisballinger** [comment]
Fixed in Fixed in https://github.com/ChatSecure/XMPPFramework/commit/5c9f1973e52690cfe8c9386d63a1e5d3ad452466
