### ISSUE TITLE
Removing a buddy sometimes requires multiple attempts.

### ISSUE THREAD

**Issue by radiosilence** [ChatSecure/ChatSecure-iOS#656]
Basically it seems like if you add someone, you remove them as a buddy before they've approved you, then a more "basic" version of the buddy still exists and needs to be removed.

1. Add a buddy.
2. Remove the buddy.
3. There is still a buddy.
4. Remove that buddy.
5. You are finally free of buddy.

**Comment by chrisballinger** [comment]
What server / software?

**Comment by mrtnhs** [comment]
Same here. Can't remove buddies. After mutiple tries they are still there. 
Server are talker.to and jabber-germany.de
Using iPhone 7 and CS 4.0

**Comment by radiosilence** [comment]
I've tried multiple. Happens on my prosody server.
