### ISSUE TITLE
Roster Request blocks chats entry ("Genehmigung ausstehend" / pending approval)

### ISSUE THREAD

**Issue by ge0rg** [ChatSecure/ChatSecure-iOS#659]
In a multi-client scenario, when I accept a contact request on another device, ChatSecure 4.0 keeps showing the contact under Chats as "<name> - Genehmigung ausstehend" (German locale). Tapping the contact does not yield any effect. The expected result would be to either

* popup a dialog to accept the request, or
* open the chat

You can chat to that contact by tapping "Compose", then selecting the contact from your roster. However, after you close the chat, you still can't tap the contact from "Chats".

**Comment by chrisballinger** [comment]
Thanks! We fixed this last week (#651) but still haven't pushed the release yet. Gonna push something to the App Store this afternoon.

https://github.com/ChatSecure/ChatSecure-iOS/commit/3c9f26aeac2ab0e91a8b9e86f68046e6e5211b85

**Comment by ge0rg** [comment]
Alright, this is fixed in 4.0.2, at least to some extent. Now, after I've accepted the roster request on another client, I still see the two buttons for accept / reject in ChatSecure, so it seems not to update the status when the presence changes.

**Comment by chrisballinger** [comment]
@ge0rg Oh like this?

1. Client 1 (alice@example.com) sends request to bob@example.com
2. Client 2 (bob@example.com) accepts request
3. Client 3 (bob@example.com) still sees request

**Comment by ge0rg** [comment]
Exactly like this 
-- 
+++ Sent from Mobile +++ https://op-co.de/ +++

**Comment by chrisballinger** [comment]
Tracking in new issue: #671
