### ISSUE TITLE
Can't initiate encrypted chat

### ISSUE THREAD

**Issue by woodpooky** [ChatSecure/ChatSecure-iOS#66]
Since updating to version 1.4, I'm unable to initiate an encrypted chat over XMPP. When "Initiate Encrypted Chat" is selected nothing happens. Occasionally it will send a blank message on initiation and freeze momentarily, but remains unencrypted and the other person does have OTR

I've tried:
Signing out and back in
Exiting app completely
Backing out of conversation and starting again
Uninstalling the app entirely and reinstalling

**Comment by ctulhoo** [comment]
Hello Chris!

Using Chatsecure Version 3.0 and latest ios 8.1.2.
registered new accounts over xmpp, gmail, xmpp with tor. Neither one is working and I cannot start encrypted chat (nothing happens when i push the button)

thanks for any help

**Comment by arpitchauhan** [comment]
I have the same issue as Chris. I'm using XMPP.
