### ISSUE TITLE
Cannot receive audio messages from Zom Android

### ISSUE THREAD

**Issue by chrisballinger** [ChatSecure/ChatSecure-iOS#660]

**Comment by chrisballinger** [comment]
Seems ok to me

**Comment by gelft** [comment]
> erver is not situated in a data center environment and its hardware and Internet channel are not duplicated for a fail-safe operation, hence its services can be inaccessible from time to time due to a network or power outage, a hardware problem, an upgrade or a reboot. Please not rely on Creep.im if the server uptime is crucial to you.
