### ISSUE TITLE
Join a exciting MUC

### ISSUE THREAD

**Issue by jnaeff** [ChatSecure/ChatSecure-iOS#667]
I need to be able to join a exciting MUC chat. This is only possible now trough a inventention by somebody else. I need to be able to do this myself.

**Comment by mimi89999** [comment]
@jnaeff Fixed in TestFlight ChatSecure 4.2 see: https://github.com/ChatSecure/ChatSecure-iOS/issues/851

@chrisballinger I think this issue can be closed.
