### ISSUE TITLE
The green circles around buddies dissappeared

### ISSUE THREAD

**Issue by mrtnhs** [ChatSecure/ChatSecure-iOS#668]
After updating to 4.0.1 the green circles around the buddies, showing an existing connection, are vanished. 
Even the green points besides a buddies name within a conversation, showing also the existing connection, are gone.

**Comment by ecky-l** [comment]
Yes, I second that. For me as well...
Besides the fact that I don't see whether the contact is online this implies also that I cannot send images or files (via OTR)

**Comment by chrisballinger** [comment]
We should have done a better job communicating this, but we are trying to de-emphasize "presence" in the UI. Everything under the hood is the same, and you can still see the circle if you press the (i) button for the profile.

We will probably add back something similar like "Last Seen". Our thinking here is that you should always be able to send a message, and that it's up to our client to properly establish the connection, negotiate crypto sessions, and handle errors.

**Comment by chrisballinger** [comment]
If a contact is fully offline, you'll still see the "Knock" button if you've previously had an OTR session with them (and they are using ChatSecure iOS).

**Comment by mrtnhs** [comment]
But it much more comfortable and much faster, if one sees the circle or anything else.
Nevertheless your app is a great thing and I'm using it more and more, convincing more and more friends of mine

**Comment by chrisballinger** [comment]
@mrtnhs Thank you for the kind words! We will definitely do some more thinking about how to improve the UX.

**Comment by vtrullinger** [comment]
I also thought this was a bug, and submitted a bug report from within the app a couple of days ago. 

One point in favor of keeping presence easily seen in the UI, is that without it, it's difficult to tell if the recipient is still present and got the message, or has logged off/gone idle and thus not seen the message you sent them. Having to drill down to their profile screen to see their presence status adds a step, whereas before that status was immediately visible at a glance. 

Maybe there could be a setting option for the user to decide whether or not they prefer to see presence status indicators?

**Comment by chrisballinger** [comment]
@vtrullinger Thanks for the feedback! We are going to do a redesign of how presence is displayed, to include information from things like chat markers, and do a better job of indicating errors when messages cannot be sent to certain offline contacts.

**Comment by chrisballinger** [comment]
Per user feedback, we've re-added indicators when contacts are available and will be included with the 4.0.3 release.
