### ISSUE TITLE
OMEMO encryption not working with contacts who use Android Conversations

### ISSUE THREAD

**Issue by ecky-l** [ChatSecure/ChatSecure-iOS#669]
The new OMEMO feature does apparently not work when the counterpart contact uses Conversations on Android. In Conversations the OMEMO option is greyed out, as it is in chatsecure for the contact on conversations. Only OTR is possible...

Best fixed together with #668 and #658, I guess...

**Comment by therob84** [comment]
Did you already try to send unencrypted messages between these devices once? Between conversations it could take 1-2 messages, until the clients recognize, that the counterpart is capable of OMEMO...

And I guess it is no general problem between Conversations<->ChatSecure, as I am quite sure, that this was tested by @chrisballinger, @inputmice and others....am I wrong?

**Comment by chrisballinger** [comment]
OMEMO definitely works both ways, but I've noticed that some servers don't send PEP updates properly so the keys don't get recognized immediately. You can force a manual PEP fetch by opening the profile (i) button.

**Comment by ecky-l** [comment]
Well, I can select OMEMO in ChatSecure contact profile (i), but my girlfriend reports that the option is still greyed out in her Conversations app. I can't send OMEMO encrypted messages to her, ChatSecure complains that there is 'no verified identity' and refuses to send the message (yellow exclamation mark besides it).

The only way is currently to use OTR, which works so far. But because the 'green circle' around online buddy's disappeared ( #668 ), I cannot (even theoretically) send images...

Is there anything to be done on the server side? I use my own prosody instance and could pimp it.

**Comment by therob84** [comment]
Image transmission between ChatSecure and Conversations is not
supported...But it will in 4.1+

Am 28. Jan. 2017 um 04:40 schrieb ecky-l:

**Comment by marmistrz** [comment]
Works in my case. I'm using Conversation, a friend of mine - ChatSecure

**Comment by gelft** [comment]
It would be awesome if you people with problems or otherwise would specify which jabber texting servers are employed.

**Comment by marmistrz** [comment]
It appeared to be another UX change in Conversations, sorry for a false report.

See Conversations issue #2295

On February 17, 2017 3:01:33 AM GMT+01:00, gelft <notifications@github.com> wrote:
>It would be awesome if you people with problems or otherwise would
>specify which jabber texting servers are employed.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ChatSecure/ChatSecure-iOS/issues/669#issuecomment-280527014

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by chrisballinger** [comment]
Closing this. Reopen if its still an issue
