### ISSUE TITLE
Multi-client roster approval synchronization issue

### ISSUE THREAD

**Issue by chrisballinger** [ChatSecure/ChatSecure-iOS#671]
1. Client 1 (alice@example.com) sends request to bob@example.com
2. Client 2 (bob@example.com) accepts request
3. Client 3 (bob@example.com) still sees request

See here: https://github.com/ChatSecure/ChatSecure-iOS/issues/659#issuecomment-275723714

**Comment by chrisballinger** [comment]
This is possibly fixed in latest commits 08fd59d4ae4d7fa2467764a6207d7076790a033a e74b8e71fd69e79eebb8393acb32f4a6bc1cea76

**Comment by mmehrle** [comment]
This issue is still plaguing me.

**Comment by mmehrle** [comment]
BTW, I'm a noob with this although I'm pretty technical. Running the latest version of ejabbered with:
mod_push: {}
mod_push_keepalive: {}

 mod_stream_mgmt:
    resend_on_timeout: true
    ack_timeout: 10
    resume_timeout: 0

I hope this is set correctly. But apparently I was mistaken to assume that push already works in the currently deployed version of ChatSecure.
