### ISSUE TITLE
chatsecure - XMPP PUSH problem

### ISSUE THREAD

**Issue by rabbit111** [ChatSecure/ChatSecure-iOS#680]
XMPP push (XEP-0357) option (xmpp server: creep.im) does not work with chatsecure (IOS, 4.02). IOS user is always offline until they open chatsecure.
PUSH option works without problems on conversations.im.
Any ideas?

**Comment by iNPUTmice** [comment]
This might be a server problem. I think they are running some running code from Github as their push module that doesn't actually do anything.

**Comment by chrisballinger** [comment]
@iNPUTmice There have been some other reports of people's personal Prosody servers not working with mod_cloud_notify, so I'm thinking we might have a client bug as well.
