### ISSUE TITLE
Server capabilities viewer

### ISSUE THREAD

**Issue by chrisballinger** [ChatSecure/ChatSecure-iOS#684]
To help users debug problems, we should provide a simple interface to view the XMPP features that their server supports. Elsewhere we should also include information about the push API registration status, push permission, and provide a "reset" option to trigger a re-registration.

**Comment by chrisballinger** [comment]
Work in progress:

![screen shot 2017-02-10 at 7 41 53 pm](https://cloud.githubusercontent.com/assets/518687/22850953/31f02a80-efc9-11e6-9e72-6033a55f3d4d.png)

**Comment by chrisballinger** [comment]
Added more info to help users debug and fix problems with push:

![screen shot 2017-02-15 at 11 25 42 am](https://cloud.githubusercontent.com/assets/518687/22991580/9eaf9272-f371-11e6-96c9-9c7d6381d0a1.png)

**Comment by gelft** [comment]
dupe https://github.com/ChatSecure/ChatSecure-iOS/issues/583
