### ISSUE TITLE
Own cert sufficient for contacting your push server?

### ISSUE THREAD

**Issue by lazyadmin111** [ChatSecure/ChatSecure-iOS#697]
Hey there,

I am running my own server with a own domain for my friends and family, but I am using my own cert as I don't want to trust any CA. Furthermore, my iOS chatsecure users experience some problems, they don't get any push notifications. To debug the problem I would like to know one thing:

Is it a requirement to have a non-own-created SSL certificate for the XMPP server to contact your push server? --- or is a own cert sufficient?

thanks for your help & great app

**Comment by chrisballinger** [comment]
The push server validates s2s certs

**Comment by chrisballinger** [comment]
I recommend you setup Let's Encrypt for your server. If you don't trust their CA, we allow you view the SHA256 fingerprint and to pin the cert in the app.
