### ISSUE TITLE
ChatSecure as the framework library?

### ISSUE THREAD

**Issue by LinkedHK** [ChatSecure/ChatSecure-iOS#706]
Hi. I just looked into  ChatSecure components,. it's quite difficult to make the independent framework library..   I just don't have enough experience to make it. any suggestions?

Thanks.

**Comment by LinkedHK** [comment]
I don't bother even to give any comment why it's been closed. nice attitude.

**Comment by chrisballinger** [comment]
Sorry, I meant to write something. There are plans to further modularize the code, but it's on the longer term roadmap and depends on external funding.
