### ISSUE TITLE
Account Cell / Detail view changes

### ISSUE THREAD

**Issue by chrisballinger** [ChatSecure/ChatSecure-iOS#713]
TODO:
- [x]  Make warning configurable so it can be hidden in Zom

* From the (i) in the account cell, it brings you to the account detail view.
* Edit Account brings you to the existing "Log In" view
* Manage My Keys shows you your OTR and OMEMO fingerprints
* Server Information, will show a ⚠️ when there is a server issue and shows this view: https://github.com/ChatSecure/ChatSecure-iOS/issues/684
* Invite Friends acts the same way as the previous "Share" button worked on the account cell.

Implications for Zom:

* There is no longer a way to set your "Default" account from the Account Cell on the Settings View. The Account Detail view could be extended for Zom and have an additional cell for showing "Default Account" or "Set as Default Account"

![simulator screen shot mar 6 2017 12 57 20 pm](https://cloud.githubusercontent.com/assets/518687/23630131/bdca61e4-026e-11e7-9eed-76722592a4dd.png)

![simulator screen shot mar 6 2017 11 54 16 am](https://cloud.githubusercontent.com/assets/518687/23630132/bde7e64c-026e-11e7-8c20-3ef6d9da02a8.png)

**Comment by cstiens** [comment]
Looks good, and the interaction are sound. One thing I would consider changing is showing 'Logout' in blue instead of red, since it's not that threatening of an action.

> There is no longer a way to set your "Default" account from the Account Cell on the Settings View. The Account Detail view could be extended for Zom and have an additional cell for showing "Default Account" or "Set as Default Account"

I think that is a good solution. Perhaps after 'Invite friends', we would show the option to 'Set as Default Account' or 'Chat with this account'.
