### ISSUE TITLE
Add key-sync suppoort

### ISSUE THREAD

**Issue by nsuchy** [ChatSecure/ChatSecure-iOS#726]
There should be a way to sync your OTR and OMEMO keys between ChatSecure iOS and between Pidgin Messenger.

**Comment by chrisballinger** [comment]
I used to think key sync might be a good idea, but it makes key revocation more difficult, and increases the chance of compromise when private keys are shared among devices. If we had key sync, it would only be used to share your trust levels of keys but not the private keys themselves.

Pidgin has proven itself to be unsafe and you should consider alternatives that aren't based on libpurple.
