### ISSUE TITLE
energy saving mode + PUSH notifications?

### ISSUE THREAD

**Issue by lazyadmin111** [ChatSecure/ChatSecure-iOS#731]
Hey folks,

I installed chatsecure 4.0 at my friend, and now push works with my server. However, it only works, if his energy saving mode is not activated, and usually it is activated. 
The surprising thing now is that he can receive messages from other messaging apps, but not from chatsecure while in energy saving mode. How can that be? Is there anything I need to do?

Any helpful comments appreciated
thank you

**Comment by chrisballinger** [comment]
Sorry, there is no remedy at the moment.

**Comment by lazyadmin111** [comment]
nevermind. But is my oberservation correct, that some apps can get push notifications even though the energy saving mode is active?

**Comment by chrisballinger** [comment]
You are correct but those apps work differently

**Comment by lazyadmin111** [comment]
Nevermind. As far as I did the best possible, everything is fine :)

**Comment by chrisballinger** [comment]
Thanks for the feedback
