### ISSUE TITLE
Build project

### ISSUE THREAD

**Issue by wellkwen** [ChatSecure/ChatSecure-iOS#750]
When trying to build a project, it produces the following errors:

`diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.`

Please tell me what to do?

**Comment by chrisballinger** [comment]
Please read the build instructions in the README.

**Comment by wellkwen** [comment]
When trying to build a project, it produces the following errors:

```
Showing Recent Errors Only
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```
Tell me what I'm doing wrong, and from what can be such a mistake?
I'm testing on my iphone 7 10.3.1, the developer account without the possibility of publishing in the app (free)
<img width="867" alt="2017-04-26 14 27 00" src="https://cloud.githubusercontent.com/assets/22137325/25432269/74512f48-2a8c-11e7-913f-e5a722324bd0.png">



And I did not understand how this paragraph is being executed, it is possible to tell in detail where to make these settings?
`You'll need to manually change the Team ID under Project -> Targets -> ChatSecure -> Signing. The old .xcconfig method doesn't seem to work well anymore.`
