### ISSUE TITLE
Build app error

### ISSUE THREAD

**Issue by wellkwen** [ChatSecure/ChatSecure-iOS#754]
When trying to build a project, it produces the following errors:

```
Showing Recent Errors Only
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Tell me what I'm doing wrong, and from what can be such a mistake?
I'm testing on my iphone 7 10.3.1, the developer account without the possibility of publishing in the app (free)
<img width="867" alt="2017-04-26 14 27 00" src="https://cloud.githubusercontent.com/assets/22137325/25432442/1e945250-2a8d-11e7-86d1-f955f3bec95b.png">

And I did not understand how this paragraph is being executed, it is possible to tell in detail where to make these settings?

`You'll need to manually change the Team ID under Project -> Targets -> ChatSecure -> Signing. The old .xcconfig method doesn't seem to work well anymore.`

**Comment by chrisballinger** [comment]
Please read the instructions in the README, or look at the .travis.yml file.

**Comment by wellkwen** [comment]
@chrisballinger , where I can find " .travis.yml file. " ?
And I did not understand how this paragraph is being executed, it is possible to tell in detail where to make these settings?

`You'll need to manually change the Team ID under Project -> Targets -> ChatSecure -> Signing. The old .xcconfig method doesn't seem to work well anymore.`

**Comment by chrisballinger** [comment]
I don't mean to seem rude but I don't have the resources to help you with your project. Please limit discussion on this tracker to software bugs and feature discussion unless you have a paid support contract.

Thank you.
