### ISSUE TITLE
Joining a conference room?

### ISSUE THREAD

**Issue by henry16** [ChatSecure/ChatSecure-iOS#77]
Hello, 

is it possible to join an openfire-hosted XMPP-based conference room?

I can chat with people on that server but not list/join rooms.

Is that a planned feature?

thanks,
henry

**Comment by sammcj** [comment]
Can this be re-opened?

I don't think there's any real demand for chat rooms to be OTR'd and it's preventing a lot of people from using it.

**Comment by chrisballinger** [comment]
It's on the roadmap

**Comment by kromcuich** [comment]
It's coming - the multiparty chat https://github.com/equalitie/np1sec
