### ISSUE TITLE
Certificate change is handled badly

### ISSUE THREAD

**Issue by gordonmessmer** [ChatSecure/ChatSecure-iOS#777]
When a server's certificate changes, ChatSecure iOS stops connecting to the server.  No indication of the problem is immediately evident.  If the user selects the account details and then "Edit Account", a pop-up indicating that the certificate has changed and allowing the user to accept the certificate will pop up.  This seems to be the only place that pop-up will appear, and it is not at all obvious that users should look here.

When using Let's Encrypt certs, this will happen every 90 days, which will become a big headache for users.

The pop-up for a new cert should pop up on any screen in the application, or it should never pop-up at all, and the application should accept any valid, signed certificate.

**Comment by chrisballinger** [comment]
Ah thanks for the reminder, this is a regression made worse by the new account details UI. As a temporary workaround you can re-use the same private key with lets encrypt, but that has other drawbacks.

It shouldn't be too hard to show the dialog throughout the application. Showing a local notification in the background may be helpful as well if you don't open the app very often.  Also showing the error directly on the account cell on the settings screen, similar to when push isn't configured properly.

**Comment by bloedersack** [comment]
I notice the same issue with Lets Encrypt. You would like to fix it in one of the next updates?

**Comment by chrisballinger** [comment]
Fix will be included in upcoming 4.1.1 release

**Comment by ncoba14** [comment]
where i can change  default server chatsecure to my server?, please..

**Comment by tristan-k** [comment]
So coming in version 4.1.1 there will be pop-up dialog - or how is it handles then?

**Comment by chrisballinger** [comment]
Yes I am having issues with a localization bug in Apple's submission
process preventing me from pushing new builds. They are "working on it"

**Comment by tristan-k** [comment]
@chrisballinger Are the changes to the way certificates are handled already merged in the latest testflight release 4.1.1 (100)?

**Comment by chrisballinger** [comment]
I think so, are you on that release?

**Comment by heurekus** [comment]
Hm, certificate approval still seems hidden and manual certificate acks are required in 4.3.6. Took me a while to figure this out. Total show stopper to recommend this app to normal users.The default must be trust in valid certificates. Great to have an option to manually approve, but it should really be an option turned off by default.
