### ISSUE TITLE
ChatSecure 4.1.0 receives empty audio message 

### ISSUE THREAD

**Issue by hemee** [ChatSecure/ChatSecure-iOS#789]
When I send audio messages to my buddy who uses Conversations, he receives it. When he sends me some, only empty message occurs. I believe it's something wrong with audio format - m4a in iOS and 3gpa (if I remember right) in Android's Conversations.

**Comment by chrisballinger** [comment]
Oh snap. I didn't test against Conversations for sending audio files. Do you have a device model?

There's a big problem with the mime types as well. Prosody's mod_http_upload will reject mime types it doesn't recognize, so the m4a files need the `audio/mpeg` type even though `audio/m4a` is more accurate.

**Comment by hemee** [comment]
Doogee X5 Max Pro, Android 6.0.

**Comment by chrisballinger** [comment]
How did he send audio? I couldn't find a way to do it from Conversations directly, so was he using a 3rd party audio recording app? There's nothing we can do to decode incompatible codecs (well, without a lot of work), so if possible your friend should configure whichever recorder app to record in MP3 or AAC format.

**Comment by hemee** [comment]
Ciitation from him: "App offers to use Sound Recorder, I though it's something supplied in the app". I never see Conversations myself, since I don't have any Android devices.

**Comment by chrisballinger** [comment]
Hmm maybe it's different on my test phone. Not sure what to do here other than ask him to use a different sound recorder?

**Comment by hemee** [comment]
Yes, I think it's the way to work it out.
