### ISSUE TITLE
Push enable request: Missing type attribute for data form

### ISSUE THREAD

**Issue by weiss** [ChatSecure/ChatSecure-iOS#793]
The `<x/>` data form submitted with the Push `<enable/>` request seems to be missing a `type` attribute (which is [mandatory][2] according to XEP-0004).

[1]: https://xmpp.org/extensions/xep-0357.html#enabling
[2]: https://xmpp.org/extensions/xep-0004.html#schema

**Comment by chrisballinger** [comment]
Fixed in 4.1.0 (87)
