### ISSUE TITLE
Pictures saving feature

### ISSUE THREAD

**Issue by hemee** [ChatSecure/ChatSecure-iOS#795]
Weird thing is that I couldn't find any way to save pictures from ChatSecure other than make a screenshot. Does it feature present?

**Comment by chrisballinger** [comment]
This only works for received messages right now, but tap their avatar and go to "Share". From there you can save to camera roll, etc.

<img width="385" alt="screen shot 2017-06-22 at 10 10 22 am" src="https://user-images.githubusercontent.com/518687/27446643-340d66d0-5733-11e7-96a7-6526e69b9d45.png">
