### ISSUE TITLE
Support XEP-0352

### ISSUE THREAD

**Issue by weiss** [ChatSecure/ChatSecure-iOS#796]
It would be nice if ChatSecure would support [XEP-0352: Client State Indication][1].  That is, send `<inactive/>` when going into the background, and `<active/>` when coming back into the foreground (if the server announced CSI support, of course).

This allows the server to queue/filter certain traffic such as PEP or presence stanzas while ChatSecure is in the background; and it can avoid some spammy push notifications for pending stream management sessions, depending on the server setup.

[1]: https://xmpp.org/extensions/xep-0352.html

**Comment by thundergreen** [comment]
+1

2017-06-22 13:55 GMT+02:00 Holger Weiß <notifications@github.com>:

**Comment by chrisballinger** [comment]
Fixed in e9208c4f
