### ISSUE TITLE
4.1.0 (87) crashes

### ISSUE THREAD

**Issue by hemee** [ChatSecure/ChatSecure-iOS#797]
App crashes immediately if you try to paste URL in the textfield.

**Comment by chrisballinger** [comment]
Thanks for the report. I am seeing this as well, but only on device.. not in simulator. Strange.

**Comment by hemee** [comment]
Look through crash logs, I've sent few. It might help to find out the problem. URL messages were duplicating in the previous build (first one was the URL itself, the second was the previewed version of it), so it maybe somehow related.

**Comment by chrisballinger** [comment]
There could be some strangeness when receiving URLs due to how media previews work. I could never get the behavior quite right.

I see the crash logs and am trying to figure out why this appeared all of a sudden...

**Comment by chrisballinger** [comment]
Strange, it I can't reproduce in simulator or device on iOS 11, but crashes regularly on device with iOS 10.

**Comment by hemee** [comment]
Well, I'm looking at the log now and see nothing that might work the issue out. Main thread causes the crash. I guess (since I'm not familiar with iOS/MacOS kernel) it's something similar to segmentation fault.

Yes, all of my devices run on iOS 10. You can try to reproduce it on iOS 10 emulator, because, well, logs give no useful information at all.

**Comment by chrisballinger** [comment]
I think I fixed it in 58c3f41008f1fecbdb61e8f0b2f9e7da680affe9
