### ISSUE TITLE
Push and self-signed Onion Cert

### ISSUE THREAD

**Issue by HenkiedeHenkie** [ChatSecure/ChatSecure-iOS#799]
I'm planning to run my own xmpp server, based on a Tor hidden service where the @onion address will serve as the username for my users. As for anonymity reasons, I don't want to rely on a third party for the certificate, so I want to self-sign my own, based on the onion address. Now, I read several issues from people concerning the working of push regarding to the use of self-signed certificates. Therefore, I'm wondering if the use of a self-signed onion certificate will form a problem for the use of push messaging with Chatsecure? Thanks!

**Comment by chrisballinger** [comment]
Push is disabled for Tor accounts because it leaks too much metadata to the push relay and to Apple. If you want push to work you must make a regular server with a valid cert. Sorry!
