### ISSUE TITLE
Setting an image as avatar on iOS app

### ISSUE THREAD

**Issue by n00b12345** [ChatSecure/ChatSecure-iOS#804]
I can't figure out how to set an avatar for my profile on the iOS app. 

(I'm the admin of my server. So I have the permissions)

**Comment by hemee** [comment]
You can't do this in the app at the moment. However, it is possible if you consider install desktop client like Gajim.

**Comment by n00b12345** [comment]
@hemee ah. Thanks :)

**Comment by mimi89999** [comment]
Any news on that? Would be nice if it was possible to set an avatar in ChatSecure.

**Comment by chrisballinger** [comment]
Thanks for the reminder

**Comment by foss-** [comment]
@chrisballinger just ran into this and thought it would be really nice to have. Should this issue here be re-opened? If so, please close this dupe afterwards:
https://github.com/ChatSecure/ChatSecure-iOS/issues/805
