### ISSUE TITLE
MUC: "Join group" leaks real jid as nick

### ISSUE THREAD

**Issue by vitalyster** [ChatSecure/ChatSecure-iOS#818]

**Comment by chrisballinger** [comment]
I believe this was intentional to facilitate OMEMO group sessions, but I can see how it may not be desirable when manually joining arbitrary rooms.

**Comment by vitalyster** [comment]
For OMEMO sessions you need MUC room configured as non-anonymous room, in this case all participants see real jids, but you should NOT set MUC nick to jid!

**Comment by chrisballinger** [comment]
Ah I see what you're saying, it could easily be set to the `displayName` property instead, which is often just the user portion of the jid. Would that be ok, or do you think users need to be able to customize their nick further before joining a room?

**Comment by vitalyster** [comment]
First of all we should read muc bookmarks and get display name from here :)
In case of new group, I think we can remove useless "password" field (it is legacy IRC compatiblilty artifact, MUC have member-only mode) and put user portion of jid there by default, allowing user to edit

**Comment by mimi89999** [comment]
@chrisballinger Not only it can be a privacy issue, but it makes tagging ChatSecure users complicated, because the bare JID is referenced....

**Comment by chrisballinger** [comment]
This issue is partially resolved in upcoming v4.1.1. It will use the account's displayName (or user portion of JID) for all MUCs instead of bare JID.

**Comment by mimi89999** [comment]
What will happen if such a nick is already used?

**Comment by chrisballinger** [comment]
@mimi89999 Good point, it's not handled. I think we'll just append some random numbers to the end of your nick until it works. Right now the nickname you use to join a room isn't persisted anywhere, so perhaps that should be changed as well.

**Comment by mimi89999** [comment]
@chrisballinger I am not able to join the MUC if an occupant with that nickname is already there... The conference will just stay gray...

**Comment by vitalyster** [comment]
Now I see other participant jids in bubble headers, where definitely must be display name too. Wonder what will be there in anonymous room.
(I think we have such issues with basic muc functionality just because Chris never uses muc in real life:))

**Comment by chrisballinger** [comment]
Heh... you're not incorrect. Improving group chat is the focus of our next sprint though, so you should start seeing some rapid improvements over the next couple of weeks, targeted for the v4.2 release.
