### ISSUE TITLE
Unread marks

### ISSUE THREAD

**Issue by vitalyster** [ChatSecure/ChatSecure-iOS#829]
Am I missing something or there is no unread marks neither in chats list nor chat itself? :)

**Comment by chrisballinger** [comment]
Never got around to adding chat markers. Tracking issue here: #512

**Comment by vitalyster** [comment]
No, it's different issue. Chat markers indicates message is read/unread by other participants, while I mean "new messages" unread by me

**Comment by vitalyster** [comment]
Like blue circle in Messages/Mail :)

**Comment by chrisballinger** [comment]
Oh, I see. In that case, the title of your contact in the chat list will remain "bold" if there are unread messages, but the effect is kind of subtle and could be improved.

**Comment by afriedmanGlacier** [comment]
This is something we'd like too, something like the blue circle in Messages/Mail
