### ISSUE TITLE
Issue Logging into GTalk with a Non Gmail Address 

### ISSUE THREAD

**Issue by m-r-davis** [ChatSecure/ChatSecure-iOS#83]
When I try to log into Google Talk with an account not ending in @gmail.com it says there is an authentication error.
Other clients such as IM+/pidgin/beejive still work properly.

Update:
I logged into the @gmail.com Account linked to that account and it logged in fine.  So it is specific to gtalk accounts not ending in @gmail.com

**Comment by errge** [comment]
@chrisballinger: can you provide some pointers on how to set up gtm-oauth2 with pidgin to log into non @gmail.com google talk?
