### ISSUE TITLE
New Messages don't appear in Inbox anymore

### ISSUE THREAD

**Issue by eil047** [ChatSecure/ChatSecure-iOS#853]
Three days ago, the new messages stopped adding up in the app's Inbox. I still get the 'New Message!' pop-ups on my iPhone but I cannot read the explicit messages anymore / they are not entering / adding to the former messages in their dedicated Inbox anymore. I did not change anything. It just suddenly changed this way in the middle of the day...?

**Comment by eil047** [comment]
Okay, I couldn't see anything abnormal but by clicking on the v sign on the right of Login there happened some renewal of a certificate and I was re-logged in and received the last messages. So everything seems back to normal again. Thanks Chris!
Luc

**Comment by chrisballinger** [comment]
Oh apologies, this is fixed in the latest betas but I haven't put out a release in a while.
