### ISSUE TITLE
Pod install issue, Xcode 8.2.1

### ISSUE THREAD

**Issue by ikyh** [ChatSecure/ChatSecure-iOS#858]
I have followed all the steps given in README, but when I open the .xcworkspace project, I get following errors:
**1.** **diff: /Podfile.lock: No such file or directory**
**2.** **diff: /Manifest.lock: No such file or directory**
**3.** **error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your 
               CocoaPods installation.**

I don't know why. I am using Xcode 8.2.1, SWIFT 3. 
Also I couldn't figure out this error **tor_cpaproxy.h file not found** despite following the solutions mentioned here [https://github.com/ChatSecure/ChatSecure-iOS/issues/345](url)

Also this semantic issue **Use of undeclared identifier 'SKStoreReviewController'**

kindly help. I am badly stuck in the first step itself. Why it has to be so complicated!

**Comment by chrisballinger** [comment]
Read the README
