### ISSUE TITLE
Crash on launch after update to 4.2.0

### ISSUE THREAD

**Issue by mimi89999** [ChatSecure/ChatSecure-iOS#863]
[ChatSecure-2017-10-25-091110.ips.txt](https://github.com/ChatSecure/ChatSecure-iOS/files/1415331/ChatSecure-2017-10-25-091110.ips.txt)

**Comment by hemee** [comment]
I experience crash when try to send OMEMO encrypted image. Actually, it doesn’t send at all.

**Comment by chrisballinger** [comment]
@hemee Thank you for the report. Have you been able to submit a crash log in the app? I am not able to reproduce on this side. Also please make another GitHub issue for this so I can track them separately.

**Comment by chrisballinger** [comment]
@mimi89999 The crash log has formatting issues from being pasted in GitHub. Would you mind email me the full file directly?

**Comment by mimi89999** [comment]
@chrisballinger I updated my comment and added the file.

**Comment by chrisballinger** [comment]
```swift
    public var threadId: String {
        if let threadId = self.roomUniqueId {
            return threadId
        } else {
            fatalError("ThreadId should not be nil!")
        }
    }
```

Somehow there is a fatal error in the database where this MUC message isn't attached to a room. I thought that this would never happen (hence the fatalError) but I guess it can in some circumstances. :-\

**Comment by mimi89999** [comment]
How could that happen? Maybe something was wrong in the older versions without good MUC support...

Could you make a release that will just drop.the problematic message from the DB?

**Comment by chrisballinger** [comment]
Yeah that's the plan

**Comment by chrisballinger** [comment]
Pushed a testflight build with a fix.

**Comment by hemee** [comment]
@chrisballinger Yea, I did sent it through crash detector. I didn’t managed to reproduce it either. Going to hard test it later today.
