### ISSUE TITLE
Deleting doesn't remove files

### ISSUE THREAD

**Issue by afriedmanGlacier** [ChatSecure/ChatSecure-iOS#865]
This might be 2 separate issues but both have to do with deleting so I'll include them here:

1) Auto-delete on disconnect does not remove any group chats from the conversations view. Not sure if this is intended and expected or not.

2) I don't think files are removed from the file system when conversations are deleted. I'm thinking they should be removed. Tested by using the GCDWebServer url and known location of media that I had received, using if([NSData dataWithContentsOfURL:mediaurl .....

I also tested with a bad url (not an existing file) just to make sure it didn't claim to exist (as it did with some other methods I tried).

EDIT: The first issue referencing group chats will be discussed in a separate issue

**Comment by hemee** [comment]
As far as I know, files are just pictures preview in the app. I think the best way to check this issue is to send multiple pics and look for memory consumption of the app.

**Comment by afriedmanGlacier** [comment]
I was thinking more from a security standpoint than a memory issue. In other words, if I am deleting conversations because I don't want any trace of those conversations on my phone, then I'd want to remove images associated with those conversations too.

**Comment by chrisballinger** [comment]
@afriedmanGlacier 

1. This is a bug
2. This can be solved with a YapDatabase relationship deletion rule.

Feel free to submit pull requests for these issues. If you'd like priority support for your organization please consider a paid support contract. Thank you.

**Comment by afriedmanGlacier** [comment]
Removed the reference to group chats in the title in order to separate these issues

**Comment by afriedmanGlacier** [comment]
Pretty sure this is fixed in pull request #873
