### ISSUE TITLE
IOS push notification with plain text

### ISSUE THREAD

**Issue by sterid** [ChatSecure/ChatSecure-iOS#894]
Hi everyone. I've just installed chatsecure on my phone. And decide that I receive IOS push notification with encoded text. Is it normal behavior? I thought if message are encrypted between two users then no plain text will be sent to apple services. And in this case nobody can read messages out of the application. 

P.s. Push notification is deactivated in server settings.

**Comment by chrisballinger** [comment]
Notifications that appear with text are decrypted locally on the device and aren't true push notifications. If the app has background refresh turned on, it will periodically wake up and download messages, decrypt and display them.
