### ISSUE TITLE
I am not receiving messages of MUC, when i was offline.

### ISSUE THREAD

**Issue by kaleemozitech** [ChatSecure/ChatSecure-iOS#913]
Is XEP-0313/XEP-0136 used or not?(MAM)

**Comment by chrisballinger** [comment]
MAM is not in the public release yet.

**Comment by MarcelWaldvogel** [comment]
@chrisballinger Is there a timeline for MAM?

**Comment by chrisballinger** [comment]
"soon"

On Thu, Mar 22, 2018 at 12:50 AM, Marcel Waldvogel <notifications@github.com

**Comment by chrisballinger** [comment]
It's approved by Apple, just need to write up some release notes.

**Comment by mimi89999** [comment]
Works fine. I think this issue can be closed now.

**Comment by kaleemozitech** [comment]
@mimi89999 you are right

**Comment by chrisballinger** [comment]
4.3.0 is out https://chatsecure.org/blog/chatsecure-v43-omemo-group-chat-preview/
