### ISSUE TITLE
Search Bar Disappears/hide after clicking on search bar in OTRComposeViewController

### ISSUE THREAD

**Issue by kaleemozitech** [ChatSecure/ChatSecure-iOS#917]
Search is working fine but when user tabs on search bar, he can't see what text is in search bar

**Comment by ethylmorphine** [comment]
Confirm. Actually, this bug is there for a very long time.

**Comment by chrisballinger** [comment]
I'm pretty sure it's new as of iOS 11

**Comment by kaleemozitech** [comment]
I am not sure but I am seeing this from a long time
