### ISSUE TITLE
no Pods fold under ChatSecure-iOs

### ISSUE THREAD

**Issue by flatworld21** [ChatSecure/ChatSecure-iOS#919]
/Users/user/Documents/ChatSecure-iOS/ChatSecure.xcodeproj The file “Pods-ChatSecureCorePods-ChatSecureCore.debug.xcconfig” couldn’t be opened because there is no such file. (/Users/user/Documents/ChatSecure-iOS/Pods/Target Support Files/Pods-ChatSecureCorePods-ChatSecureCore/Pods-ChatSecureCorePods-ChatSecureCore.debug.xcconfig)

**Comment by chrisballinger** [comment]
read the instructions...
