### ISSUE TITLE
ignore ressources / priority

### ISSUE THREAD

**Issue by jalogisch** [ChatSecure/ChatSecure-iOS#922]
I just searched the issues and stumbled on this https://github.com/ChatSecure/ChatSecure-iOS/issues/68

Have two seperate accounts, each one is connected from a different (iOS) device. One is connected from my Mac using Adium.

**Account A** -> Connected from Adium (Prio: 50 / Ressource: Mac)
**Account A** -> Connected from Chatsecure App

**Account B** -> Connected from Chatsecure App

I can initiate a Chat from **Account A** from any connected Client and it will go to **Account B**. 

When I then reply to **Account A** from **Account B** the message is lost when the Chatsecure App **Account A** is not active or the client is total disconnected. I would expect that the message is routed to Adium client.

My XMPP Server is a self-hosted prosody that has all modules enable to that are needed to get all lights green on the server check page in Chatsecure.

Maybe I'm just missing something, but this way it does not work as I expect. If you need additional Information, just let me know.

**Comment by chrisballinger** [comment]
I think you'll need to activate MAM for this to work in the way you described, but I'm pretty sure Adium doesn't have MAM support and our MAM support is still in beta, although shipped in the TestFlight builds.

**Comment by jalogisch** [comment]
even with activated MAM ... I'll see if it will work in future. Thank you.

**Comment by jalogisch** [comment]
found XEP-0280 that would solve my issue in some better way. 

( https://xmpp.org/extensions/xep-0280.html ) Maybe it would be nice to have that optional enabled.

**Comment by chrisballinger** [comment]
XEP-0280 is already supported on the client, but it requires support on your server as well.

**Comment by jalogisch** [comment]
prosody installation on debian with prosody modules installed has that available. 

I'll just close that issue here. 

It is not always working 100% reliable, but enough for me
