### ISSUE TITLE
Tor after sign-in without tor enabled

### ISSUE THREAD

**Issue by LorenzoPanico** [ChatSecure/ChatSecure-iOS#925]
Hi, is there a way to use tor after signup without tor enabled?

**Comment by chrisballinger** [comment]
No, you'll need to write down your username/password, delete the account, and then go to Add Existing Account.

**Comment by LorenzoPanico** [comment]
And if i use delete message, will it be removed even from the addressee(he has not seen it and its still pending approval

**Comment by chrisballinger** [comment]
Depends on how the server is set up. Message deletion is purely a client side behavior.

**Comment by LorenzoPanico** [comment]
Im using otr.im, do you if does work?
