### ISSUE TITLE
Logo for ChatSecure made on Utopian platform

### ISSUE THREAD

**Issue by andrejcibik** [ChatSecure/ChatSecure-iOS#928]
Hello,
this my design of logo for your project. Its free. Created on Utopian platform where users are rewarded for contributions to open-source projects. 

https://utopian.io/utopian-io/@andrejcibik/logo-for-chatsecure-open-source-private-chat-ios-app

You dont have to accept it or anything. But if you like it, spread the good work about the platform :) 

Andy

**Comment by vitalyster** [comment]
Is it possible to view it without registration, or at least with GitHub account?

**Comment by andrejcibik** [comment]
Oh.... I forgot. Sorry. 
Here is the same content on different website https://busy.org/utopian-io/@andrejcibik/logo-for-chatsecure-open-source-private-chat-ios-app

**Comment by chrisballinger** [comment]
Thanks for the thought, and looks pretty decent! Seems like a good exercise for up and coming graphic designers. Unfortunately I'm not sure how much success you'll have with offering projects unsolicited radical rebranding because it's kind of a big deal to make those sort of changes. You may have better luck contacting project maintainers privately before undergoing the design process to see how you could best contribute. 

Good luck!

**Comment by jubalh** [comment]
For what it's worth: it looks much better than the current one ;D

**Comment by vitalyster** [comment]
@jubalh maybe it looks "better" as is, but it doesn't fit in current style of ChatSecure - it needs much more work to create the whole style and it is not just a logo

**Comment by Echolon** [comment]
@vitalyster Yes, but I think, as a first step, you could change the Logo and then you'll see. Cool logo is better than nothing. I mean, the app design is very basic (what totally okay!) Thus, a logo change wouldn't matter that much imo

**Comment by andrejcibik** [comment]
You are copletely right @chrisballinger. As the wording implies, it is not just meant to be for you, but also as a "tutorial" of how to create such a logo. It took me 2h :D That not really enough for a serious rebranding. Im aware of that. 

However, if you wanted to make an overall rebranding, you could register, create a task request and community would create a shitload of designs ....for free. They are payed using Steem platform.

**Comment by chrisballinger** [comment]
Brand recognition is a big deal and goes beyond just a simple logo change. Yes the original logo is sort of outdated and could use a facelift, but drastically changing the branding we've had for 5+ years is a big risk.

There is a way to [allow alternative icons](https://www.hackingwithswift.com/example-code/uikit/how-to-change-your-app-icon-dynamically-with-setalternateiconname) at runtime in iOS 10.3 or higher, but to be honest I don't see myself implementing that any time soon. There are too many other high priority problems, and too few developers familiar with the code to help fix them.

@andrejcibik I don't quite understand how people are getting paid using this platform. Where does the money come from?

**Comment by andrejcibik** [comment]
Once the time comes, you know where to get it for free :) 

"Where does the money come from? " :D haha, thats the first question people have.
Steem is an economic system based on cryptocurrency. In Bitcoin, newtokens are rewarded to the miners for their work. In Steem, new tokens are distributed by the users, to the users based on how much they like the content.

Its meant to be an uncesorable social network where you get paid, but its much more. As you can see .... people contribute to open source projects.

**Comment by Echolon** [comment]
Should this really be closed? I mean, it shouldnt be forgotten at least
