### ISSUE TITLE
Chatsecure is still on 4.2.1 in the Appstore

### ISSUE THREAD

**Issue by sirdrakeistda** [ChatSecure/ChatSecure-iOS#933]
I don't know if it is the intent that Chatsecure is still 4.2.1 in the Appstore. But there are also 4.2.2 and 4.3. So please update Chatsecure. And thank you for your great work.

**Comment by Echolon** [comment]
I guess they have reasons for not releasing a new stable... and since I follow the development of ChatSecure, they usually release not that frequently, which isn't meant negative.

Just wait and/or donate/contribute.

**Comment by ethylmorphine** [comment]
You should consider anticipating in beta-testing. After this you will understand why there are no frequent updates.

**Comment by chrisballinger** [comment]
Trust me I've wanted to ship a new version for a while but I keep hitting snags. I probably should have cut a stable release of v4.2.2 but it was never quite ready, and then a bunch of new features got piled on. I wanted to ship a new beta yesterday but had a regression from a recent pull request that causes very long pauses on launch. Software development can be very frustrating and thankless work. Waiting for new stable releases can be a bother, but so can a crash on launch bug that we didn't catch during QA.

Please sign up for the TestFlight beta group if you want early access (to potentially unstable builds): https://goo.gl/forms/tFJrXnKTmmJGxY6h1

**Comment by Echolon** [comment]
@chrisballinger Thanks for your response - I appreciate your work - thus, release first when you're okay with the status of the release. Take your time, as ChatSecure really needs to work very very good in an iOS/Apple environment.

Thank you!
