### ISSUE TITLE
[Bug] Push Registration info is broken

### ISSUE THREAD

**Issue by ethylmorphine** [ChatSecure/ChatSecure-iOS#976]
![Image](https://i.imgur.com/Pxu9jx8.jpg)
You will see loading icon only no matter how long you wait.

**Comment by ethylmorphine** [comment]
P.S. The version is the latest 4.3.0 (126) beta.

**Comment by ethylmorphine** [comment]
Aaaand pushes don’t work either :( dismail.de server.

**Comment by chrisballinger** [comment]
Having some issues with the server all of a sudden. 

<img width="1194" alt="screen shot 2018-03-20 at 7 37 29 am" src="https://user-images.githubusercontent.com/518687/37661246-982c1090-2c11-11e8-8609-9078cab541e9.png">

<img width="1201" alt="screen shot 2018-03-20 at 7 39 16 am" src="https://user-images.githubusercontent.com/518687/37661348-d614d1bc-2c11-11e8-9efd-d752b875f98a.png">

**Comment by chrisballinger** [comment]
Sigh... it's that time of the year again. The APNS certificate expired and the updated cert didn't load properly.

**Comment by ethylmorphine** [comment]
Sounds like it’s not a big deal though.

**Comment by chrisballinger** [comment]
Yeah I just forgot that when updating the APNS certificate env var you'll need to push a new empty commit to Heroku otherwise the old certificate will be cached across dyno restarts. Should be fixed now.
